### ISSUE TITLE
ONL install not support ONIE new structure

### ISSUE THREAD

**Issue by delta-JohnsonLu** [opencomputeproject/OpenNetworkLinux#244]
When I install ONL on a switch with latest ONIE installed, the python script of "platform/current.py" of packages/base/all/vendor-config-onl/src/python/onl, needs to parse /etc/machine.conf with "onie_platform=" string. However, the latest version of ONIE machine.conf is revised by nesting other configure files, machine-build.conf, which lacks of onie_platform, kindly refer to machine.conf in https://github.com/opencomputeproject/onie/blob/master/rootconf/default/etc/machine.conf. May I know if there is a plan to keep up with ONIE change!

**Comment by sonoble** [comment]
Hello, 

We will look into the issue and provide a solution. 

Our ONIE support policy is to test against the latest ONIE release. This change appears in master, not the latest ONIE release 2017.08.01br.

**Comment by Lewis-Kang** [comment]
Hi Steven,

Any update on this issue? Thanks.

**Comment by MellanoxBSP** [comment]
Hi Steve,

We are facing the same problem with ONIE release 2017.11br

Thanks.

**Comment by jnealtowns** [comment]
This issue has been resolved.
