### ISSUE TITLE
What happened to ORC?

### ISSUE THREAD

**Issue by tustvold** [opencomputeproject/OpenNetworkLinux#302]
I'm fairly new to the world of networking let alone bare-metal switching, so I could be missing something very fundamental, but I'm struggling to work out how to get even a simple bridge network up on an AS4610-54T (which is listed in various places as supported).

Following installation the front panel ports don't appear as network interfaces, which I believe is to be expected as they are not directly visible to Linux, but instead are managed by a dedicated Broadcom ASIC. The documentation, however, makes reference to ORC and my understanding is that this is/was a RTNETLINK based daemon that exposed the front panel ports as standard linux network interfaces and allowed management using standard linux facilites such as network scripts.

I built the latest sources for Debian 8 using the provided docker build system, which I must say I really like, and installed the armel artifact onto the switch, however, orc doesn't appear to exist anymore? I'm aware of various alternatives such as FBOSS, SAI, etc... but none of these are really the same nor do they support the switch in question as far as I can decipher.

As part of further investigating this issue I installed a trial of Cumulus Linux and their switchd seems to do the same thing that I understand ORC does/did. However, the general attitude of Cumulus linux to security I found somewhat troubling. You have to install all packages from their apt repo, for which their is no out of band way to confirm their GPG key, and which does not appear to be kept up to date with the Debian repos. Installing packages from the Debian repos causes switchd to malfunction, and so you are reliant on Cumulus Linux to keep their software patched. This to me seems very akin to the vendor lock-in and associated detrimental effects on security and innovation that I was hoping bare-metal switches addressed?

Any help on how best to proceed would be much appreciated, a colleague and I have wasted the best part of a week bashing our heads against this problem to no avail. I notice that Cumulus linux comes with a load of kernel modules that are LGPL licensed - is it just a case of building these, installing them and then building and installing orc, or will this not work?

**Comment by aaglenn** [comment]
ORC (Open Route Cache) is indeed a simple daemon between the Broadcom SDK and Linux Netlink, but intended as a demonstrative starting point to developing your own.

**Comment by hex-m** [comment]
There is a message regarding ORC on the [mailing-list](https://groups.google.com/d/msg/opennetworklinux/gym5K1DEL3c/NBZyXcKfBgAJ):

> We no longer support orc as it became very hard to maintain as we updated ONL to version 2.0 and moved to the 3.16 kernel.

**Comment by tustvold** [comment]
Ok, thank you for clarifying.
