### ISSUE TITLE
Build issue in make ONL

### ISSUE THREAD

**Issue by doicom** [opencomputeproject/OpenNetworkLinux#306]
Hello.
I am trying to build ONL  of amd64 on debian8.8.
However, the error occurred according to the making procedure and the binary of ONL was not able to be made.

The procedure is as follows.

# >git clone https://github.com/opencomputeproject/OpenNetworkLinux
# >cd OpenNetworkLinux
# >docker/tools/onlbuilder -8         
# >apt-cacher-ng
# >source setup.env 
# >make amd64        #error with this command

root@debian:/OpenNetworkLinux# make amd64
make -C builds/amd64
make[1]: Entering directory '/OpenNetworkLinux/builds/amd64'
GEN pkgall
INFO:onlpm:Requiring prerequisite package onlp:amd64...
INFO:onlpm:Requiring prerequisite package onl-kernel-3.16-lts-x86-64-all:amd64...
INFO:onlpm:Requiring prerequisite package onl-kernel-4.9-lts-x86-64-all:amd64...
INFO:onlpm:Requiring prerequisite package onl-loader-initrd:amd64...
INFO:onlpm:Requiring prerequisite package onl-buildroot-initrd:amd64...
INFO:onlpm:Requiring prerequisite package onl-loader-initrd-files:all...
INFO:onlpm:Requiring prerequisite package onl-kernel-3.16-lts-x86-64-all:amd64...
INFO:onlpm:Requiring prerequisite package onl-kernel-4.9-lts-x86-64-all:amd64...
INFO:onlpm:Requiring prerequisite package onl-loader-initrd:amd64...
INFO:onlpm:Requiring prerequisite package onl-buildroot-initrd:amd64...
INFO:onlpm:Requiring prerequisite package onl-loader-initrd-files:all...
INFO:onlpm:Requiring prerequisite package onl-vendor-config-quanta:all...
INFO:onlpm:Requiring prerequisite package onl-vendor-config-onl:all...
INFO:onlpm:Requiring prerequisite package onl-bootd:all...
INFO:onlpm:Requiring prerequisite package onl-platform-modules-x86-64-quanta-ix1b-rglbmc:amd64...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO:onlpm:Requiring prerequisite package onl-vendor-alphanetworks-modules:amd64...
INFO:onlrfs:Updating /OpenNetworkLinux/REPO/jessie/packages/binary-amd64
DEBUG:onlrfs:Executing:make -C /OpenNetworkLinux/REPO/jessie/packages/binary-amd64
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Updating Package Manifest...
dpkg-scanpackages: info: Wrote 205 entries to output Packages file.
INFO:onlrfs:Updating /OpenNetworkLinux/REPO/jessie/packages/binary-all
DEBUG:onlrfs:Executing:make -C /OpenNetworkLinux/REPO/jessie/packages/binary-all
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Updating Package Manifest...
dpkg-scanpackages: info: Wrote 19 entries to output Packages file.
DEBUG:onlrfs:Executing:sudo rm -rf rootfs-amd64.d
DEBUG:onlrfs:Executing:sudo /usr/sbin/multistrap -d rootfs-amd64.d -f /tmp/tmp2S56Z1
Use of uninitialized value in join or string at /usr/sbin/multistrap line 1280.
Use of uninitialized value in join or string at /usr/sbin/multistrap line 1280.
multistrap 2.2.0 using /tmp/tmp2S56Z1
multistrap 2.2.0 using /tmp/tmp2S56Z1
Defaulting architecture to native: amd64
multistrap building amd64 multistrap on 'amd64'
I: Setting /OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/lib64 -> /OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/lib symbolic link.
Getting package lists: apt-get  -o Apt::Architecture=amd64 -o Dir::Etc::TrustedParts=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/trusted.gpg.d -o Dir::Etc::Trusted=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/trusted.gpg.d/trusted.gpg -o Apt::Get::AllowUnauthenticated=true -o Apt::Get::Download-Only=true -o Apt::Install-Recommends=false -o Dir=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/ -o Dir::Etc=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/ -o Dir::Etc::Parts=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/apt.conf.d/ -o Dir::Etc::PreferencesParts=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/etc/apt/preferences.d/ -o APT::Default-Release=* -o Dir::State=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/lib/apt/ -o Dir::State::Status=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/lib/dpkg/status -o Dir::Cache=/OpenNetworkLinux/builds/amd64/rootfs/builds/rootfs-amd64.d/var/cache/apt/ update
Ign copy: ./ InRelease
Ign copy: ./ InRelease                       
Ign copy: ./ Release.gpg                     
Ign copy: ./ Release.gpg                     
Ign copy: ./ Release                         
Ign copy: ./ Release                         
Get:1 copy: ./ Packages [11.0 kB]            
Ign copy: ./ Translation-en                                             
Get:2 copy: ./ Packages [134 kB]              
Ign copy: ./ Translation-en                                                   
Ign http://127.0.0.1:3142 jessie InRelease      
Ign http://127.0.0.1:3142 unstable InRelease
Ign http://127.0.0.1:3142 jessie Release.gpg
Ign http://127.0.0.1:3142 unstable Release.gpg
Ign http://127.0.0.1:3142 jessie Release
Ign http://127.0.0.1:3142 unstable Release
Err http://127.0.0.1:3142 jessie/main amd64 Packages                          
  401  Unauthorized
Ign http://127.0.0.1:3142 jessie/main Translation-en                          
Err http://127.0.0.1:3142 unstable/main amd64 Packages     
  401  Unauthorized
Ign http://127.0.0.1:3142 unstable/main Translation-en
Fetched 145 kB in 0s (648 kB/s)
W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Packages  401  Unauthorized
W: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages  401  Unauthorized
E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev rootfs-amd64.d/dev
DEBUG:onlrfs:Executing:sudo mount -t proc proc rootfs-amd64.d/proc
mount: mount point rootfs-amd64.d/proc does not exist
DEBUG:onlrfs:Executing:sudo umount -l rootfs-amd64.d/dev rootfs-amd64.d/proc
umount: rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not mount proc in new filesystem.
/OpenNetworkLinux/make/rfs.mk:36: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/OpenNetworkLinux/tools/onlpm.py", line 1265, in <module>
    pm.build(p)
  File "/OpenNetworkLinux/tools/onlpm.py", line 951, in build
    products = pg.build(dir_=dir_)
  File "/OpenNetworkLinux/tools/onlpm.py", line 610, in build
    self.gmake_locked("", 'Build')
  File "/OpenNetworkLinux/tools/onlpm.py", line 585, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/OpenNetworkLinux/tools/onlu.py", line 70, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make

I think the cause is a proxy setting.
However, I do not know which file to change 

Please help me with you ideas.

**Comment by capveg** [comment]
Hi,

The lines:

> Fetched 145 kB in 0s (648 kB/s)
> W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Packages 401 Unauthorized
> W: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages 401 Unauthorized
> E: Some index files failed to download. They have been ignored, or old ones used instead.

Indicate there is some sort of problem reaching the main debian repositories from your build machine.  Are you by chance behind a firewall or proxy?  If the later, check out the docs directory for how to build behind a proxy.

**Comment by doicom** [comment]
Thank Rob

With your advice , I was able to create ONL.
The cause was proxy setting.
Thank you

The created ONL debian_version was 8.10
If I created ONL in Debian 8.8 ,will the ONL debian_version be 8.10?

**Comment by capveg** [comment]
Kind of the entire point of the ONL build system is that the resulting build image should be independent of your build environment.  So, no, if you build ONL v8, you should get 8.10 independent of your base version.

**Comment by doicom** [comment]
Thank Rob
Thank you for the advice a lot.
