### ISSUE TITLE
The built ONL image still container the proxy address in the apt sources list

### ISSUE THREAD

**Issue by basilsaji-rtb** [opencomputeproject/OpenNetworkLinux#351]
Hi All,

The buillt ONL image container the proxy link appended to the actual link even after its loaded into the box and has to be manually edited. Can this be corrected?

src http://127.0.0.1:3142/apt.opennetlinux.org/debian/ 

Regards
Basil

**Comment by jnealtowns** [comment]
Its a bug in the RFS definition for the ONL section. Thanks for the report
we'll fix it!
