### ISSUE TITLE
Accton ONLP Locator LED control

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#360]
Current Accton OPNLP library for x86-64-accton-as7312-54xs-r0 would not allow to turn Locator LED on or off using ONLP libray API although onlp_led_info_get() call returns a structure where capability ONLP_LED_CAPS_ON_OFF is indicated. Both API's onlp_led_set() and onlp_led_mode_set() return error ONLP_STATUS_E_UNSUPPORTED.

My code:
```
// 1 - on, 0 - off
int COTS_onlp_Locator_LED_Ctl (int on_off)
{
	int rc = 0;
	onlp_oid_t cid;
	onlp_led_mode_t mode = (on_off) ? (ONLP_LED_MODE_ON) : (ONLP_LED_MODE_OFF);
	onlp_led_info_t led_info;

	debug_log (VXOS_TRACE_DEBUG, "START on_off=%d mode=%d\n", on_off, mode);
	cid = ONLP_LED_ID_CREATE(2);

	rc = onlp_led_info_get(cid, &led_info);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 cid=%d onlp_led_info_get rc=%d\n", cid, rc);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 cid=%d description='%s'\n", cid, led_info.hdr.description);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 cid=%d mode=%d\n", cid, led_info.mode);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 cid=%d caps=%d 0x%08X\n", cid, led_info.caps, led_info.caps);

	rc = onlp_led_set(cid, on_off);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 id=%d cid=%d onlp_led_set on_off=%d rc=%d\n", Led_OIDs[1], cid, on_off, rc);

	rc = onlp_led_mode_set(cid, mode);
	debug_log (VXOS_TRACE_DEBUG, "LED 2 id=%d cid=%d onlp_led_mode_set mode=%d rc=%d\n", Led_OIDs[1], cid, mode, rc);
	return (rc);
}
```

My trace if this code execution:

COTS_onlp_Locator_LED_Ctl:228 LED 2 cid=83886082 onlp_led_info_get rc=0
COTS_onlp_Locator_LED_Ctl:229 LED 2 cid=83886082 description='Chassis LED 2 (LOC LED)'
COTS_onlp_Locator_LED_Ctl:230 LED 2 cid=83886082 mode=0
COTS_onlp_Locator_LED_Ctl:231 LED 2 cid=83886082 caps=4097 0x00001001
COTS_onlp_Locator_LED_Ctl:234 LED 2 id=83886082 cid=83886082 onlp_led_set on_off=1 **rc=-10**
COTS_onlp_Locator_LED_Ctl:237 LED 2 id=83886082 cid=83886082 onlp_led_mode_set mode=1 **rc=-10**
ERROR:HAL:s_halserver_proc_set_loc_led_rq:273 Error setting Locator LED to ON. rc=-10

Capabilities are 4097 or 0x00001001 - (ONLP_LED_CAPS_ON_OFF and ONLP_LED_CAPS_ORANGE)
but LED is not possible to turn ON.

**Comment by roylee123** [comment]
Hi,  
I've put the fix to https://github.com/opencomputeproject/OpenNetworkLinux/pull/366.
It can fix the error on calling onlp_led_set() with  on_off=1.

**Comment by Vladimir-NTCT** [comment]
Verified: fix for Locator LED works. Thank you.

**Comment by Vladimir-NTCT** [comment]
Closing issue.
