### ISSUE TITLE
Could you please provide a KVM or VirtualBox x86_64 image for testing?

### ISSUE THREAD

**Issue by q2dg** [opencomputeproject/OpenNetworkLinux#365]
Thanks a lot!

**Comment by jnealtowns** [comment]
@q2dg Please start with the following guide for building the ONIE KVM platform:
https://opencomputeproject.github.io/onie/design-spec/x86_virtual_machine.html?highlight=kvm

Once you have the ONIE KVM platform running (x86-64-kvm-x86-64-r0) you can install ONL on it.

**Comment by q2dg** [comment]
Thanks. In fact, I followed these steps you mention but I didn't success as it can be seen here: https://github.com/opencomputeproject/onie/issues/735
Anyway, thanks. I'll close the issue, then, if you don't mind
