### ISSUE TITLE
Question: Are ONLP API's thread safe?

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#369]
Are ONLP API's reenter-able and thread safe?
Or user processes calling ONLP  should have protection mechanism themselves?

This question is especially important in regard to Transceivers read and write operations.

**Comment by jnealtowns** [comment]
The client ONLP APIs are protected by a global shared mutex. All users of the onlp_* APIs have automatic concurrency protection from all processes in the system without the requirement for local protection mechanisms. 

When writing the underlying ONLP platform implementation (sfpi, fani, psui, etc) you are guaranteed that your implementation vectors will never be called concurrently.

**Comment by Vladimir-NTCT** [comment]
Thank you.

Vladimir Cherednichenko
Sr. Software Engineer

[PastedGraphic-1]


178 E. Tasman Drive
San Jose, CA 95134

DIRECT +14085856943
www.netscout.com<http://www.netscout.com/>
