### ISSUE TITLE
ONLP onlp_sfp_eeprom_read shifts QSFP EEPROM data

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#376]
libonlp-x86-64-accton-as7312-54x.so
Gives QSFP EEPROM data properly:

Accton 7312:

Port 53 onlp_sfp_eeprom_read rc=0 sfp_eeprom=0x1aca3c0
QSFP: Dump 256 bytes
:    0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 0d 00 00 0f 00 00 00 00 00 00 00 00 00 00 00 00    ?..?............
10: 00 00 00 00 00 00 17 87 00 00 81 89 00 00 00 00    ......??..??....
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00    .............?..
60: 00 00 00 00 f0 0f 00 f1 f0 00 00 00 00 00 00 00    ....??.??.......
70: 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00    ................
80: 0d 10 0c 04 00 00 00 40 40 02 00 05 67 00 00 32    ????...@@?.?g..2
90: 00 00 00 00 46 49 4e 49 53 41 52 20 43 4f 52 50    ....FINISAR CORP
A0: 20 20 20 20 07 00 90 65 46 54 4c 34 31 30 51 45        ?.?eFTL410QE
B0: 32 43 20 20 20 20 20 20 41 20 42 68 07 d0 46 97    2C      A Bh??F?
C0: 00 01 04 d0 4d 51 50 30 35 4c 4e 20 20 20 20 20    .???MQP05LN
D0: 20 20 20 20 31 34 30 31 31 30 20 20 0a 00 00 53        140110  ?..S
E0: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

Vendor info is full and at appropriate offsets: 
Vendor offset 148 (0x94), length 16
Part Number at 168 (0xA8) length 16
Serial number at 196 (0xC4) length 16

The same function call with libonlp-x86-64-accton-wedge100bf-32x.so with the same Transceiver inserted gives incorrect data.

Accton Wedge100BF:

Port 0 onlp_sfp_eeprom_read rc=0 sfp_eeprom=0x7f53000008e0
QSFP: Dump 256 bytes
:    0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 0d 00 00 00 00 00 00 00 00 00 00 18 00 81 00 00    ?..........?.?..
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
30: 00 00 00 00 00 00 00 00 00 00 00 00 ff ff ff ff    ................
40: 0d 0c 00 00 40 00 67 00 00 00 46 4e 53 52 43 52    ??..@.g...FNSRCR
50: 20 20 07 90 46 4c 31 51 32 20 20 20 41 42 07 46      ??FL1Q2   AB?F
60: 00 04 4d 53 32 4c 20 20 20 20 31 30 31 20 0a 00    .?MS2L    101 ?.
70: 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00            ........
80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................

Vendor name starts at 0x4A and has every other symbol skipped. Same for other vendor info.
It seems that every other byte of the EEPROM is missing.

**Comment by Vladimir-NTCT** [comment]
Found it:

https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/sfpi.c

Lines 172 – 182.

For (i=0;  i < 128; i++0) {
     Int bus = sfp_bus_index(port);
     Int val = onlp_i2c_readw(bus, devadr, i*2, ONLP_I2C_F_FORCE);

     If (val < 0) {
           return ONLP_STATUS_E_INTERNAL;
     }

     data[i] = val &0xFF;
     data[i+1] = (val >>8) &0xFF;
}

They read a two-byte word from Transceiver EEPROM then move data to the read buffer which is uint8_t data[256];
Each step of the loop they write 2 bytes to the buffer overwriting second byte just written on the previous step.

Needs to be modified as:

                data[i*2] = = val &0xFF;
                data[(i*2)+1] = (val >>8) &0xFF;

**Comment by phani-karanam** [comment]
Replaced data[i] and data[i+1] with data[i*2] and data[(i*2)+1] respectively in sfpi.c file. After replacing, connected the innolight transceiver to Accton Wedge100BF_32x SFP port to read the SFP EEPROM and data can be read correctly. Also same innolight transceiver was connected to AS7312_54XS device for testing and both Accton Wedge100BF_32x SFP EEPROM data and  AS7312_54XS SFP EEPROM data are same except some real time data.

**Comment by Vladimir-NTCT** [comment]
With that fix function works. Transceiver EEPROm is read properly.
