### ISSUE TITLE
x86-64-accton-wedge100bf-32x-r0 - set LED mode - wrong color

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#377]
I am using ONLP library libonlp-x86-64-accton-wedge100bf-32x.so to control LED's on the front panel of  Barefoot Wedge 100BF-32X.
'Chassis LED 1 (SYS LED 2)' is used as a "Locator" LED since this platform does not have a designated locator as some others.
Call to onlp_led_info_get() for this LED returns capabilities 0x000F0C01 which means:
    ONLP_LED_CAPS_ON_OFF = (1 << 0),
    ONLP_LED_CAPS_RED = (1 << 10),
    ONLP_LED_CAPS_RED_BLINKING = (1 << 11),
    ONLP_LED_CAPS_GREEN = (1 << 16),
    ONLP_LED_CAPS_GREEN_BLINKING = (1 << 17),
    ONLP_LED_CAPS_BLUE = (1 << 18),
    ONLP_LED_CAPS_BLUE_BLINKING = (1 << 19),

To set LED 2 blinking I am using onlp_led_mode_set().
When mode is ONLP_LED_MODE_GREEN_BLINKING it is OK - LED id blinking green as requested.

But when mode is set to ONLP_LED_MODE_RED_BLINKING it is actually blinking BLUE.
And the other way around:  when mode is set to  ONLP_LED_MODE_BLUE_BLINKING it is blinking RED.

Mode ONLP_LED_MODE_OFF is turning it off as requested.

**Comment by phani-karanam** [comment]
In **OpenNetworkLinux/packages/platforms/accton/x86-64/x86-64-accton-wedge100bf-32x/onlp/builds/src/module/src/ledi.c**,  replaced  {ONLP_LED_MODE_**RED**, 0x1},  {ONLP_LED_MODE_**RED**_BLINKING, 0x9}, with {ONLP_LED_MODE_**BLUE**, 0x1},
    {ONLP_LED_MODE_**BLUE**_BLINKING, 0x9} respectively,  and also replaced {ONLP_LED_MODE_**BLUE**, 0x4},
    {ONLP_LED_MODE_**BLUE**_BLINKING, 0xc},   with  {ONLP_LED_MODE_**RED**, 0x4},
    {ONLP_LED_MODE_**RED**_BLINKING, 0xc} respectively.          After replacing,RED and BLUE LEDs can turn on and blink correctly for System LED1 & LED2.

**Comment by phani-karanam** [comment]
This issue is already fixed in **https://github.com/opencomputeproject/OpenNetworkLinux/pull/398**. So, please close this issue.
