### ISSUE TITLE
This installer does not support the powerpc-as5700-96x-r01 platform.

### ISSUE THREAD

**Issue by elpamyelhsa** [opencomputeproject/OpenNetworkLinux#381]
Open Network Installer running under ONIE.
Installer Version: Open Network Linux 89f17d8 (powerpc.all,2017.10.02.18.47,89f17d8df68f835d1341f1c083466f70da8a6f64)
Detected platform: powerpc-as5700-96x-r01

Full Console Output
[ONL.txt](https://github.com/opencomputeproject/OpenNetworkLinux/files/1973314/ONL.txt)

This installer does not support the powerpc-as5700-96x-r01 platform.
Available platforms are:
powerpc-accton-as4600-54t-r0
powerpc-accton-as5610-52x-r0
powerpc-accton-as5700-96x-r0
powerpc-accton-as5710-54x-r0
powerpc-accton-as6700-32x-r0
powerpc-accton-as6700-32x-r1
powerpc-as4600-54t
powerpc-as5600-52x
powerpc-as5610-52x
powerpc-as5710-54x-r0a
powerpc-as5710-54x-r0b
powerpc-as6700-32x-r0
powerpc-dni-7448-r0
powerpc-quanta-lb9-r0
powerpc-quanta-lb9a-r0
powerpc-quanta-ly2-r0
Installation cannot continue.

**Comment by elpamyelhsa** [comment]
Would it help if I could provide hardware specifications?
Could it be the same hardware as the powerpc-accton-as5700-96x-r0?

**Comment by sonoble** [comment]
Hello,

Do you know the difference between r0 and r01?  Normally edge-core adds the platforms.  You could potentially install the r0 version, but without knowing the changes there is no guarantee that it would work correctly.

**Comment by diwu1989** [comment]
Did this ever get resolved?
The powerpc-as5700-96x-r01 is a device that was never really fully sold, but I see it on eBay for really cheap these days:
https://www.ebay.com/itm/EDGE-CORE-5700-96X-FP1AO5696000A-5700-SERIES-96-PORT-10G-SWITCH-AS5700-96X/264774849335

Can we confirm whether the two variants of the powerpc-accton-as5700-96x-r0 are supported or not?
