### ISSUE TITLE
ONL build issue

### ISSUE THREAD

**Issue by reju85** [opencomputeproject/OpenNetworkLinux#383]
Hi,
I am not able to build ONl source code ..Kindly help
**Steps Done**

#> git clone https://github.com/opencomputeproject/OpenNetworkLinux
#> cd OpenNetworkLinux
#> export VERSION=8
#> make docker

**Error**

INFO:onlrfs:dpkg-configure filesystem...
DEBUG:onlrfs:Executing:sudo chroot rootfs-powerpc.d /tmp/configure.sh
chroot: failed to run command '/tmp/configure.sh': No such file or directory
DEBUG:onlrfs:Executing:sudo umount -l rootfs-powerpc.d/dev rootfs-powerpc.d/proc
INFO:onlrfs:[profiler] sudo umount -l rootfs-powerpc.d/dev rootfs-powerpc.d/proc : 0.0785911083221 seconds (0.00130985180537 minutes)
ERROR:onlrfs:Post Configuration failed.
/home/user/Open_Network_Lin/OpenNetworkLinux/make/rfs.mk:36: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/home/user/Open_Network_Lin/OpenNetworkLinux/tools/onlpm.py", line 1277, in <module>
    pm.build(p)
  File "/home/user/Open_Network_Lin/OpenNetworkLinux/tools/onlpm.py", line 962, in build
    products = pg.build(dir_=dir_)
  File "/home/user/Open_Network_Lin/OpenNetworkLinux/tools/onlpm.py", line 621, in build
    self.gmake_locked("", 'Build')
  File "/home/user/Open_Network_Lin/OpenNetworkLinux/tools/onlpm.py", line 596, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/home/user/Open_Network_Lin/OpenNetworkLinux/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/home/user/Open_Network_Lin/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/user/Open_Network_Lin/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/user/Open_Network_Lin/OpenNetworkLinux/builds/powerpc'
Makefile:23: recipe for target 'powerpc' failed
make: *** [powerpc] Error 2
make: *** [docker] Error 2

**Comment by tzuyun629** [comment]
Hi @reju85 
I encountered the same issue.

```
onlpm.OnlPackageError: 'Build failed.'
/home/emma/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/emma/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/emma/OpenNetworkLinux/builds/powerpc'
Makefile:23: recipe for target 'powerpc' failed
make: *** [powerpc] Error 2
Makefile:56: recipe for target 'docker' failed
make: *** [docker] Error 2
root@emma-VirtualBox:/home/emma/OpenNetworkLinux#
```

How did you fix it?
