### ISSUE TITLE
unable to "build by hand"

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#41]
root@CicadaBuildServer:/home2/kang/OCP/OpenNetworkLinux# docker/tools/onlbuilder -8
[ ok ] Enabling additional executable binary formats: binfmt-support.
root@CicadaBuildServer:/home2/kang/OCP/OpenNetworkLinux# source setup.env
bash: setup.env: No such file or directory
root@CicadaBuildServer:/home2/kang/OCP/OpenNetworkLinux# ls -la
total 8
drwxr-xr-x 2 root root 4096 Feb 17 04:24 .
drwxr-xr-x 3 root root 4096 Feb 17 04:24 ..

**Comment by sonoble** [comment]
Hi Kang, 

What are the files in the directory, it looks empty? Also in general it is best if  you build as a normal user rather than root.

**Comment by jnealtowns** [comment]
Lewis,

When you run onlbuilder in interactive mode

**Comment by jnealtowns** [comment]
Lewis,

When you run onlbuilder in interactive, non-isolate mode only your $HOME
directory is mounted by default.

If your tree is elsewhere then you'll need to use the --volumes option to
mount additional directories:

#> onlbuilder --volumes /home2/kang -8

This situation seems to happen often enough that we will modify the default
behavior when invoking onlbuilder to include both your $HOME directory and
the current working directory from which onlbuilder was invoked.

Jeff

**Comment by jnealtowns** [comment]
Lewis, 

This behavior has been modified:
https://github.com/opencomputeproject/OpenNetworkLinux/pull/42

**Comment by Lewis-Kang** [comment]
thanks!
