### ISSUE TITLE
HCL update for Interface Masters platforms.

### ISSUE THREAD

**Issue by vitalivanov** [opencomputeproject/OpenNetworkLinux#44]
Please update HCL for IMT by adding OpenNSL as vendor provided binaries - Yes***.
We have them for all the platforms.

Broadcom providing it for our HW thru github but for 3.5.0.54 kernel and only for n2948-6xl. IMT provides them for any platforms that we have under ONL.

**Comment by sonoble** [comment]
I have put in a pull request : https://github.com/opencomputeproject/OpenNetworkLinux/pull/45 does that look correct? Provided by you for all but the last platform which is supported by the public OpenNSL release
