### ISSUE TITLE
HCL update for Accton/Edge-Core platforms

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#46]
Hi Steven,

Could you help update HCL for Accton/Edge-Core platforms by the following? Thanks in advance.

1. Adding OpenNSL as vendor provided binaries - Yes*** for AS4600-54T,  AS5710-54X, AS5712-54X, AS6712-32X and AS7712-32X.

2. Adding OF-DPA as vendor provided binaries - Yes*** for AS5712-54X, AS6712-32X and AS7712-32X

**Comment by sonoble** [comment]
Hi Lewis,

Sorry for the delay, I have created a pull request https://github.com/opencomputeproject/OpenNetworkLinux/pull/47 let me know if that looks right.  You can also view the document directly here:

https://github.com/sonoble/OpenNetworkLinux/blob/doc_updates/docs/SupportedHardware.md

Thanks

**Comment by sonoble** [comment]
Hi Again,

I accidentally included OFDPA support for platforms that we do not provide it for.  Can you check my link and see if I have it correct?

**Comment by Lewis-Kang** [comment]
Hi Steven,

Yes. It's correct. Thanks

**Comment by sonoble** [comment]
Great thanks!
