### ISSUE TITLE
libonlp-x86-64-accton-as7712-32x.so - onlp_psu_info_get() did not return power supply present

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#486]
Code:

	for (i = 0; i < Psu_OIDs_cnt; ++i)
	{
		cid = ONLP_PSU_ID_CREATE(i+1);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d id=%d cid=%d\n", i+1, Psu_OIDs[i], cid);
		rc = onlp_psu_info_get(cid, &psu_info);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d onlp_psu_info_get rc=%d\n", i+1, cid, rc);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d description='%s'\n", i+1, cid, psu_info.hdr.description);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d status=%d\n", i+1, cid, psu_info.status);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d caps=%d 0x%08X\n", i+1, cid, psu_info.caps, psu_info.caps);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d mvin=%d\n", i+1, cid, psu_info.mvin);
		debug_log (VXOS_TRACE_DEBUG, "PSU %d cid=%d mvout=%d\n", i+1, cid, psu_info.mvout);
	}

Trace

Nov 19 22:51:36 vss-kbp-proto hal_main[463]: PSU
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: onlp_psu_init rc=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:178 PSU 1 id=67108865 cid=67108865
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: Unable to read PSU(1) node(psu_present)
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:180 PSU 1 cid=67108865 onlp_psu_info_get rc=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:181 PSU 1 cid=67108865 description='PSU-1'
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:182 PSU 1 cid=67108865 status=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:183 PSU 1 cid=67108865 caps=0 0x00000000
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:184 PSU 1 cid=67108865 mvin=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:185 PSU 1 cid=67108865 mvout=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:178 PSU 2 id=67108866 cid=67108866
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: Unable to read PSU(2) node(psu_present)
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:180 PSU 2 cid=67108866 onlp_psu_info_get rc=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:181 PSU 2 cid=67108866 description='PSU-2'
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:182 PSU 2 cid=67108866 status=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:183 PSU 2 cid=67108866 caps=0 0x00000000
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:184 PSU 2 cid=67108866 mvin=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:185 PSU 2 cid=67108866 mvout=0
Nov 19 22:51:36 vss-kbp-proto hal_main[463]: EMERGENCY:HAL:COTS_Init_ONLP:189

**Comment by Vladimir-NTCT** [comment]
Looks like ONLP library is looking for non-existing file. There is no file "psu_present" in a filesystem for both PSU1 and PSU2

# cd /sys/bus/i2c/devices/11-005b/
# ls -al
total 0
drwxr-xr-x 3 root root    0 Nov 19 22:51 .
drwxr-xr-x 5 root root    0 Nov 19 22:51 ..
lrwxrwxrwx 1 root root    0 Nov 19 22:51 driver -> ../../../../../../bus/i2c/drivers/ym2651
drwxr-xr-x 3 root root    0 Nov 19 22:51 hwmon
-r--r--r-- 1 root root 4096 Nov 19 23:28 modalias
-r--r--r-- 1 root root 4096 Nov 19 23:28 name
-rw-r--r-- 1 root root 4096 Nov 19 23:28 psu_fan1_duty_cycle_percentage
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_fan1_fault
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_fan1_speed_rpm
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_fan_dir
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_i_out
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_id
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_iin_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_iout_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_model
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_pin_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_pout_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_revision
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_vin_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_vin_min
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_vout_max
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_mfr_vout_min
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_over_temp
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_p_out
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_pmbus_revision
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_power_good
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_power_on
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_temp1_input
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_temp_fault
-r--r--r-- 1 root root 4096 Nov 19 23:28 psu_v_out
lrwxrwxrwx 1 root root    0 Nov 19 22:51 subsystem -> ../../../../../../bus/i2c
-rw-r--r-- 1 root root 4096 Nov 19 22:51 uevent

# cd /sys/bus/i2c/devices/10-0058
# ls -al
total 0
drwxr-xr-x 3 root root    0 Nov 19 22:51 .
drwxr-xr-x 5 root root    0 Nov 19 22:51 ..
lrwxrwxrwx 1 root root    0 Nov 19 22:51 driver -> ../../../../../../bus/i2c/drivers/ym2651
drwxr-xr-x 3 root root    0 Nov 19 22:51 hwmon
-r--r--r-- 1 root root 4096 Nov 19 23:27 modalias
-r--r--r-- 1 root root 4096 Nov 19 23:27 name
-rw-r--r-- 1 root root 4096 Nov 19 23:27 psu_fan1_duty_cycle_percentage
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_fan1_fault
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_fan1_speed_rpm
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_fan_dir
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_i_out
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_id
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_iin_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_iout_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_model
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_pin_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_pout_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_revision
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_vin_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_vin_min
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_vout_max
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_mfr_vout_min
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_over_temp
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_p_out
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_pmbus_revision
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_power_good
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_power_on
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_temp1_input
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_temp_fault
-r--r--r-- 1 root root 4096 Nov 19 23:27 psu_v_out
lrwxrwxrwx 1 root root    0 Nov 19 22:51 subsystem -> ../../../../../../bus/i2c
-rw-r--r-- 1 root root 4096 Nov 19 22:51 uevent

**Comment by Vladimir-NTCT** [comment]
I do not have onlpdump
# onlpdump
-sh: onlpdump: not found
#

We have 2 AC power supplies. 
/sys/bus/i2c/devices/10-0050/ and /sys/bus/i2c/devices/11-0053 are both empty:

# cd /sys/bus/i2c/devices/10-0050
# pwd
/sys/bus/i2c/devices/10-0050
# ls -al
total 0
drwxr-xr-x 2 root root    0 Nov 19 22:51 .
drwxr-xr-x 5 root root    0 Nov 19 22:51 ..
-r--r--r-- 1 root root 4096 Nov 19 23:18 modalias
-r--r--r-- 1 root root 4096 Nov 19 23:18 name
lrwxrwxrwx 1 root root    0 Nov 19 22:51 subsystem -> ../../../../../../bus/i2c
-rw-r--r-- 1 root root 4096 Nov 19 22:51 uevent
# cd /sys/bus/i2c/devices/11-0053
# pwd
/sys/bus/i2c/devices/11-0053
# ls -al
total 0
drwxr-xr-x 2 root root    0 Nov 19 22:51 .
drwxr-xr-x 5 root root    0 Nov 19 22:51 ..
-r--r--r-- 1 root root 4096 Nov 19 23:18 modalias
-r--r--r-- 1 root root 4096 Nov 19 23:18 name
lrwxrwxrwx 1 root root    0 Nov 19 22:51 subsystem -> ../../../../../../bus/i2c
-rw-r--r-- 1 root root 4096 Nov 19 22:51 uevent
#
Driver ym2651 puts PSU info into /sys/bus/i2c/devices/10-0058 and /sys/bus/i2c/devices/11-005b
there is no "psu_present" file in both.

I2C devices are instantiated boot time by shell script as follows:
# initiate PSU-1
echo as7712_32x_psu 0x53 > /sys/bus/i2c/devices/i2c-11/new_device
echo ym2651 0x5b > /sys/bus/i2c/devices/i2c-11/new_device

# initiate PSU-2
echo as7712_32x_psu 0x50 > /sys/bus/i2c/devices/i2c-10/new_device
echo ym2651 0x58 > /sys/bus/i2c/devices/i2c-10/new_device

Accton kernel drivers loaded:
x86_64_accton_as7712_32x_sfp     7333  0
x86_64_accton_as7712_32x_leds     4079  0
x86_64_accton_as7712_32x_psu     2814  0
x86_64_accton_as7712_32x_fan     4365  0
accton_i2c_cpld         6102  5 vss_driver,x86_64_accton_as7712_32x_leds,x86_64_accton_as7712_32x_fan,x86_64_accton_as7712_32x_psu,x86_64_accton_as7712_32x_sfp
ym2651y                 5545  0
gpio_ich                3704  0

Please confirm that this is correct.

**Comment by roylee123** [comment]
Hi, 
1. Model ids should be specified with index.
echo as7712_32x_psu1 0x53 > /sys/bus/i2c/devices/i2c-11/new_device
echo as7712_32x_psu2 0x50 > /sys/bus/i2c/devices/i2c-10/new_device

2. As replied, psu_present are not @/sys/bus/i2c/devices/10-0058 and /sys/bus/i2c/devices/11-005b.
They are at /sys/bus/i2c/devices/10-0050/psu_present and /sys/bus/i2c/devices/11-0053/psu_present, respectively.

Besides, no onlp_psu_info_get() inside libonlp-x86-64-accton-as7712-32x.so. 
If you want to call onlp_psu_info_get(), you should load libonlp.so.

# nm /lib/platform-config/x86-64-accton-as5812-54x-r0/onl/lib/libonlp-x86-64-accton-as5812-54x.so
...
0000000000015f52 T onlp_ledi_mode_set
0000000000015f14 T onlp_ledi_set
00000000000159b8 T onlp_psui_info_get
..

**Comment by Vladimir-NTCT** [comment]
roylee123 

Changing 
echo as7712_32x_psu 0x53 > /sys/bus/i2c/devices/i2c-11/new_device
echo as7712_32x_psu 0x50 > /sys/bus/i2c/devices/i2c-10/new_device
to
echo as7712_32x_psu1 0x53 > /sys/bus/i2c/devices/i2c-11/new_device
echo as7712_32x_psu2 0x50 > /sys/bus/i2c/devices/i2c-10/new_device
helps.
This resolve this issue.
