### ISSUE TITLE
ONL bring up apt-update issue

### ISSUE THREAD

**Issue by shakeel7** [opencomputeproject/OpenNetworkLinux#541]
Hi,

I have installed ONL ( **ONL-2.0.0-ONL-OS-DEB8-2017-07-18.1642-40fc82b-AMD64-INSTALLED-INSTALLER** ) on a QEMU VM. 
It seems there is no shared library package available for ONL.
apt, wget, and every other normal Linux commands are throwing an error ( 
 **error while loading shared libraries: libapt-pkg.so.4.12: cannot open shared object file: No such file or directory** )
I have assigned IP to ONL using **dhclient eth1** command. 
Is there any way i can access ONL from a terminal so that i can transfer the relevant files to the system and get it working.?
Also, using a flash drive seems not a working way as this is in a nested VM.
Could someone give thoughts on this? Thanks.

**Comment by jnealtowns** [comment]
I would be happy to try to help you if this issue persists and you can provide useful information about your VM.
