### ISSUE TITLE
Should systemd call `/etc/boot.d/boot` script?

### ISSUE THREAD

**Issue by Yi-Tseng** [opencomputeproject/OpenNetworkLinux#546]
As far as I know, in inittab (for sysvinit) calls `/etc/boot.d/boot` when the system started
However, the systemd does not. 
Should we add ONL init script (systemd service) for systemd?

**Comment by jnealtowns** [comment]
@Yi-Tseng A proper fix for this issue has been provided by https://github.com/opencomputeproject/OpenNetworkLinux/commit/3f4bb55187b475d98e661a01197552674f0fd1fb

**Comment by Yi-Tseng** [comment]
@jnealtowns Thanks for the support, I'll test it in our lab ASAP.
