### ISSUE TITLE
When will x86_64_accton_AS5916_54xmk_r0 be supported?

### ISSUE THREAD

**Issue by giddyup888** [opencomputeproject/OpenNetworkLinux#559]
Hi
I have recently acquired accton_5916_54xmk, and trying to install the latest ONL pkge, but failed.
and found that the latest ONL pkg doesn't have support for 5916_xmk yet.
anyone has any idea when it will be supported?
what needs to be done in order to support that model in ONL?
I apologize for asking so fundamental questions, I am new to the group.
many thanks for the help.
Fei-

Apr 22 04:11:48 onie-host local0.info os-install: modprobe: can't change directory to '/lib/modules': No such file or directory
Apr 22 04:11:48 onie-host local0.info os-install: Archive:  /tmp/sfx-QTOuXF/onie-installer.zip
Apr 22 04:11:48 onie-host local0.info os-install:   inflating: preinstall.sh
Apr 22 04:11:48 onie-host local0.info os-install: Hello from preinstall
Apr 22 04:11:48 onie-host local0.info os-install: Chroot is /tmp/sfx-QTOuXF/initrd-pWRbuQ
Apr 22 04:11:49 onie-host local0.info os-install: Traceback (most recent call last):
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/bin/onl-install", line 6, in <module>
Apr 22 04:11:49 onie-host local0.info os-install:     import onl.install.App
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 21, in <module>
Apr 22 04:11:49 onie-host local0.info os-install:     import ConfUtils, BaseInstall
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/ConfUtils.py", line 14, in <module>
Apr 22 04:11:49 onie-host local0.info os-install:     from onl.sysconfig import sysconfig
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/sysconfig/__init__.py", line 13, in <module>
Apr 22 04:11:49 onie-host local0.info os-install:     from onl.platform.current import OnlPlatform
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 81, in <module>
Apr 22 04:11:49 onie-host local0.info os-install:     OnlPlatform = import_subsystem_platform_class()
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 76, in import_subsystem_platform_class
Apr 22 04:11:49 onie-host local0.info os-install:     m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
Apr 22 04:11:49 onie-host local0.info os-install:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Apr 22 04:11:49 onie-host local0.info os-install:     __import__(name)
**Apr 22 04:11:49 onie-host local0.info os-install: ImportError: No module named x86_64_accton_as5916_54xmk_r0**
Apr 22 04:11:48 onie-host local0.info os-install: 65287 blocks
Apr 22 04:11:48 onie-host local0.info os-install: modprobe: can't change directory to '/lib/modules': No such file or directory

**Comment by jnealtowns** [comment]
This is something that needs to be addressed by EdgeCore. Thus far support for this system has not been submitted to ONL.
