### ISSUE TITLE
[ONLPv2] function onlp_attribute_onie_info_get is not protected by lock.

### ISSUE THREAD

**Issue by ryanliou72** [opencomputeproject/OpenNetworkLinux#566]
Hi

The function onlp_attribute_onie_info_get in attributei.c is not protected by global lock.

In our case, we using i2c read to get onie eeprom data in this functin.
And it will fail because no protection on this function.

Do you plan to add ONLP lock into this function in future?

Thank you for your reply.
Ryan

**Comment by jnealtowns** [comment]
@ryanliou72  Yes, it should be locked. I will fix it.

**Comment by jnealtowns** [comment]
Resolved in https://github.com/opencomputeproject/OpenNetworkLinux/commit/d896122156502a519f113aa72d00a2438afde9e5
