### ISSUE TITLE
x86-64-cel-redstone-xp platform-config ONIE grub error

### ISSUE THREAD

**Issue by pimpajr** [opencomputeproject/OpenNetworkLinux#57]
I was checking ONL out on a switch in my lab, it's not directly on the HCL, but its a cel_redstone_xp platform so I figured I'd give it a shot. After a seemingly successful install and first couple of boots working fine I decided to check if I could boot back into ONIE. Selecting ONIE at grub it gives an error about chainloader1. I edited the grub entry and changed it to chainloader +1 and got into ONIE, so I think this is just a typo. 
I looked it up at https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/celestica/x86-64/x86-64-cel-redstone-xp/platform-config/r0/src/lib/boot/grub.cfg#L19 
and noticed it seems to be chainloader +1 on all the other platform configs except this one.

**Comment by sonoble** [comment]
Hi!

Thanks for the bug report, I have updated the master https://github.com/opencomputeproject/OpenNetworkLinux/commit/07b6d0cd34a9023c698c70ae45f2500349ab3f77

**Comment by pimpajr** [comment]
Cool looks good, thanks for the quick fix.
