### ISSUE TITLE
Netberg Aurora 620 not supported

### ISSUE THREAD

**Issue by wido** [opencomputeproject/OpenNetworkLinux#573]
According to the HCL ( http://opennetlinux.org/hcl) the Netberg Aurora 620 is supported, but it doesn't seem to work.

During the install:

<pre>
Jul  1 07:29:08 onie local0.info os-install: The operation has completed successfully.
Jul  1 07:29:08 onie local0.info os-install: Traceback (most recent call last):
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/bin/onl-install", line 6, in <module>
Jul  1 07:29:08 onie local0.info os-install:     import onl.install.App
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 21, in <module>
Jul  1 07:29:08 onie local0.info os-install:     import ConfUtils, BaseInstall
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/ConfUtils.py", line 14, in <module>
Jul  1 07:29:08 onie local0.info os-install:     from onl.sysconfig import sysconfig
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/sysconfig/__init__.py", line 13, in <module>
Jul  1 07:29:08 onie local0.info os-install:     from onl.platform.current import OnlPlatform
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 81, in <module>
Jul  1 07:29:08 onie local0.info os-install:     OnlPlatform = import_subsystem_platform_class()
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 76, in import_subsystem_platform_class
Jul  1 07:29:08 onie local0.info os-install:     m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
Jul  1 07:29:08 onie local0.info os-install:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Jul  1 07:29:08 onie local0.info os-install:     __import__(name)
Jul  1 07:29:08 onie local0.info os-install: ImportError: No module named x86_64_huracan_aurora_620_rangeley_r0
</pre>

It seems the Netberg is detected as a Huracan Aurora 620 and not Netberg.

**Comment by sonoble** [comment]
Hi Wido,

We do not know of any changes but @andrewsapronov or @sergeypopovich-ord may have input here.  There are ways to modify the machine name to get ONL to install, but we don't know what the difference if any are between the two machines.

**Comment by wido** [comment]
@sonoble Thanks for the feedback!

I'd like to trick the ONL install to think it's a different platform just to see how it works. Can you point me to the right direction on how to do this?

**Comment by sonoble** [comment]
@wido you will need to replace huracan with netberg. Depending on the version of ONIE you are running you will either do this in machine.conf or in the machine-build.conf, both are in the /etc directory in ONIE Rescue mode.  The install should go through but there is no guarantee that the system will work as we do not know what the changes are.

Here is the relevant part of machine.conf off of a 2017 ONIE

ONIE:/etc # more machine.conf
onie_version=master-201706060118
onie_vendor_id=47294
onie_platform=x86_64-netberg_aurora_620_rangeley-r0
onie_machine=netberg_aurora_620_rangeley
onie_machine_rev=0
onie_arch=x86_64

**Comment by RPDiep** [comment]
@sonoble 
Colleague of @wido here,
I've already tried that and the install completes.
After booting however, there are multiple error messages:
```
FOXCONN is not Mellanox ... failed!
```

```
Loading kernel module i2c-dev.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module i2c-dev not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module pmbus.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module pmbus not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module tps53679.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module tps53679 not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module max1363.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module max1363 not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module coretemp.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module coretemp not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module lm75.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module lm75 not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module tmp102.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module tmp102 not found in directory /lib/modules/3.16.64-OpenNetworkLinux
Loading kernel module ledtrig-timer.
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.16.64-OpenNetworkLinux/modu'
modprobe: FATAL: Module ledtrig-timer not found in directory /lib/modules/3.16.64-OpenNetworkLinux
```
As I merely was tricking the installer, I assumed these messages were because of hardware differences.
Maybe this is a later hardware version. On the (non-public) netberg ftp site, I saw the name huracan also.

**Comment by sonoble** [comment]
Hi @RPDiep I think the people I tagged earlier are the best to help.  I don't know what the huracan system differences are.  You can do lspci and provide the output if you would like.

**Comment by RPDiep** [comment]
Attached output of `lspci -v` and `dmidecode`.

[lspci-v.txt](https://github.com/opencomputeproject/OpenNetworkLinux/files/3346930/lspci-v.txt)
[dmidecode.txt](https://github.com/opencomputeproject/OpenNetworkLinux/files/3346931/dmidecode.txt)

**Comment by sonoble** [comment]
Hi @RPDiep 

The box you have has a different Broadcom chipset, the BCM56967 vs the BCM56963 in the one in the ONL lab.  It also has a newer revision of the CPU.  We will need to wait for Netberg to respond.

**Comment by andrewsapronov** [comment]
Hi, 

Dear @wido and @RPDiep,  there are some SKU differ in IDs with identical hardware. It is connected with proprietary ICOS solutions and depends on software stack which purchase. 

So, if you are planning to use an open source solutions like ONL you also need to use vanilla [ONIE](https://github.com/opencomputeproject/onie/tree/master/machine/netberg/netberg_rangeley_p1330). 

The right way is to build (machine name called netberg_rangeley_p1330) and [burn](https://github.com/opencomputeproject/onie/blob/master/machine/netberg/netberg_rangeley_p1330/INSTALL) ONIE by ourselves or you can just [get](https://netbergtw.com/wp-content/uploads/Files/github-onie-recovery-x86_64-netberg_rangeley_p1330-r0.iso) pre-build the ONIE image.

In any way you can just connect to support@netbergtw.com with all questions and for proprietary ONIE image for restoring back ICOS solution.

**Comment by jochenschniepp-stordis** [comment]
Don't worry about:
> FOXCONN is not Mellanox ... failed!

That's caused by the proprietary Mellanox start/kill script hw-management. That might be required to controll the fan speed on Mellanox hardware and you will see this message on any switch other than Mellanox if the script is launched. However I have to agree that sounds quite critical, but it isn't at all.
Apparently, in the meantime - and luckily - this script has been removed via amd64-base-packages.yml, so that should no longer been seen.
FOXCONN comes from a RO file in /sys/devices/virtual/dmi/id/ and will be set during installation of the BIOS. That should be zero related with ONL and Netberg should better request a customized BIOS from FOXCONN to get this clean.
