### ISSUE TITLE
No module named powerpc_quanta_ly8_p2020_r0

### ISSUE THREAD

**Issue by brevius** [opencomputeproject/OpenNetworkLinux#600]
Hi,
Is it possible to built ONL for this platform?
LY8 U-Boot
  Product Name              : LY8

  Part Number               : 1LY8BZZ0ST4

  Manufacture Date          : 09/23/2015
  Device Version            : 1
  HW Board Version          : D3C
  Platform Name             : P2020FNOR128D4G
  ONIE Version              : 2014.05.03-7a00c05
  Number of MAC             : 67
  Manufacturer              : QSMC
  Country Code              : CN
  Vendor                    : QCI
  Diag Software Version     : 1.0.6.0
  Diag Software Code        : 0x1060f801
  Model Name                : QUANTA LY8

CPLD Version: Dev#1=00305319

U-Boot 2010.12 (Oct 03 2014 - 14:38:07) - ONIE 2014.05.03-7a00c05

CPU0:  P2020, Version: 2.1, (0x80e20021)
Core:  E500, Version: 5.1, (0x80211051)
Clock Configuration:
       CPU0:1200 MHz, CPU1:1200 MHz, 
       CCB:600  MHz,
       DDR:400  MHz (800 MT/s data rate) (Asynchronous), LBC:37.500 MHz
L1:    D-cache 32 kB enabled
       I-cache 32 kB enabled
Board: Quanta COMMON P2020, Rev C (Boot from NorFlash)
Send CPU Boot OK (Active Low)
I2C:   ready
SPI:   ready
DRAM:  Detected UDIMM TS256MSK72V3N     
Detected UDIMM(s)
DDR: 2 GiB (DDR3, 64-bit, CL=6, ECC on)
SD/MMC : 4-bit Mode
FLASH: 128 MiB
L2:    512 KB enabled
MMC:  FSL_ESDHC: 0

Jul 14 07:05:30 onie local0.info os-install: Hello from preinstall
Jul 14 07:05:30 onie local0.info os-install: Chroot is /tmp/sfx-Y8vbcm/initrd-T9rMHO
Jul 14 07:05:32 onie local0.info os-install: Traceback (most recent call last):
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/bin/onl-install", line 6, in <module>
Jul 14 07:05:32 onie local0.info os-install:     import onl.install.App
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 21, in <module>
Jul 14 07:05:32 onie local0.info os-install:     import ConfUtils, BaseInstall
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/install/ConfUtils.py", line 14, in <module>
Jul 14 07:05:32 onie local0.info os-install:     from onl.sysconfig import sysconfig
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/sysconfig/__init__.py", line 13, in <module>
Jul 14 07:05:32 onie local0.info os-install:     from onl.platform.current import OnlPlatform
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 81, in <module>
Jul 14 07:05:32 onie local0.info os-install:     OnlPlatform = import_subsystem_platform_class()
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 76, in import_subsystem_platform_class
Jul 14 07:05:32 onie local0.info os-install:     m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
Jul 14 07:05:32 onie local0.info os-install:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Jul 14 07:05:32 onie local0.info os-install:     __import__(name)
Jul 14 07:05:32 onie local0.info os-install: ImportError: No module named powerpc_quanta_ly8_p2020_r0

**Comment by bombshellnetworks** [comment]
Im in the same boat.  QuantaMesh T5032-LY6

Launching ONL installer
Extracting from /tmp/sfx-RQ8mR1/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-RQ8mR1/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-RQ8mR1/initrd-Owbx9m
Examining /dev/mmcblk0p1 -->
Examining /dev/sda1 -->
Traceback (most recent call last):
  File "/usr/bin/onl-install", line 6, in <module>
    import onl.install.App
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 21, in <module>
    import ConfUtils, BaseInstall
  File "/usr/lib/python2.7/dist-packages/onl/install/ConfUtils.py", line 14, in <module>
    from onl.sysconfig import sysconfig
  File "/usr/lib/python2.7/dist-packages/onl/sysconfig/__init__.py", line 13, in <module>
    from onl.platform.current import OnlPlatform
  File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 81, in <module>
    OnlPlatform = import_subsystem_platform_class()
  File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 76, in import_subsystem_platform_class
    m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named powerpc_quanta_ly6_p2020_r0
Install failed.

**Comment by jnealtowns** [comment]
@brevius @bombshellnetworks  These require support from the Quantamesh team. Since they have not commented I will close this request and you must follow up with then.
