### ISSUE TITLE
compile error while building onlp lib -- because of new update in AIM module

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#62]
make -C packages/base/amd64/onlp
make[1]: Entering directory `/home2/kang/OCP_0318/OpenNetworkLinux/packages/base/amd64/onlp'
INFO:onlpm:Requiring prerequisite package onlp:amd64...
INFO:onlpm:Rebuilding onlp:amd64...
make[2]: Entering directory `/home2/kang/OCP_0318/OpenNetworkLinux/packages/base/amd64/onlp/builds'
    Compiling[ release ]: AIM::aim_daemon.c
    Compiling[ release ]: onlplib::i2c.c
    Compiling[ release ]: onlp_platform_defaults::sfpi.c
    Compiling[ release ]: onlp_platform_defaults::sysi.c
    Compiling[ release ]: sff::sff.c
    Compiling[ release ]: sff::sff_enums.c
    LinkingShared[release]: libonlp-platform-defaults-module::libonlp-platform-defaults.so
    Compiling[ release ]: AIM::aim_daemon.c
    Compiling[ release ]: onlplib::i2c.c
    Compiling[ release ]: onlp_platform_defaults::sfpi.c
    Compiling[ release ]: onlp_platform_defaults::sysi.c
    Compiling[ release ]: sff::sff.c
    Compiling[ release ]: sff::sff_enums.c
    LinkingShared[release]: libonlp-platform-module::libonlp-platform.so
    Compiling[ release ]: AIM::aim_daemon.c
    Compiling[ release ]: onlplib::i2c.c
    Compiling[ release ]: onlp::fan.c
    Compiling[ release ]: onlp::led.c
    Compiling[ release ]: onlp::onlp_config.c
In file included from /home2/kang/OCP_0318/OpenNetworkLinux/sm/infra/modules/AIM//module/src/aim_daemon.c:26:0:
/home2/kang/OCP_0318/OpenNetworkLinux/sm/infra/modules/AIM//module/inc/AIM/aim_config.h:333:2: error: #error AIM_CONFIG_INCLUDE_DAEMONIZE requires AIM_CONFIG_INCLUDE_MAIN. Disable AIM_CONFIG_INCLUDE_DAEMONIZE or enable AIM_CONFIG_INCLUDE_MAIN.

**Comment by Lewis-Kang** [comment]
How about removing the following line in _**packages/base/any/onlp/builds/onlp/Makefile**_
GLOBAL_CFLAGS += -DAIM_CONFIG_INCLUDE_DAEMONIZE=1

**Comment by sonoble** [comment]
Hi Lewis, I am not sure that is the solution.  The issue seems to have been introduced with the update of the infra repository.  I am tracking it down.

**Comment by jnealtowns** [comment]
Apologies - I will look into this this morning.

**Comment by jnealtowns** [comment]
@Lewis-Kang Removing that from the ONLP build configuration is the correct action. It was never used before but is now obviously failing due to the new consistency check. 

Fixed as of https://github.com/opencomputeproject/OpenNetworkLinux/commit/653ccf525e4b8e0f1213c9e4ce1b2746ec5b5f07

**Comment by Lewis-Kang** [comment]
Thanks
