### ISSUE TITLE
'make docker' Error message -> can not create onlp-x86-64-accton-as7716-32x-r0_1.0.0_amd64.deb

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#64]
INFO:onlpm:Rebuilding onlp-x86-64-accton-as7716-32x-r0:amd64...
make[3]: Entering directory `/home/kang/OCP_0321/OpenNetworkLinux/packages/platforms/accton/x86-64/x86-64-accton-as7716-32x/onlp/builds'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
/home/kang/OCP_0321/OpenNetworkLinux/sm/infra/builder/unix/dependmodules.mk:65: /x86_64_accton_as7716_32x.mk: No such file or directory
make[4]: *** **No rule to make target `/x86_64_accton_as7716_32x.mk'.**  Stop.
make[3]: *** [all] Error 1
make[3]: Leaving directory `/home/kang/OCP_0321/OpenNetworkLinux/packages/platforms/accton/x86-64/x86-64-accton-as7716-32x/onlp/builds'
**ERROR**:onlpm:'Build failed.'
/tmp/tmpggTNlDE**RROR**:onlrfs:Failed to build all required packages.

**Comment by capveg** [comment]
Just to be clear -- did you figure out the problem here?  If so, just for
tracking, what was it (even if it was just a local problem)?

- Rob
.

**Comment by Lewis-Kang** [comment]
Rob,

Thanks for tracking.

I did git pull to get all latest files and then `make docker` and got this error. My college said he git clone the repo didn't have this error. So this issue should be my local build environment is not clean enough. I don't know where(under which folder) I should do 'make clean' to resolve this issue without using a 'heavy' git clone yet...

If you know the answer, please enlighten me. Thanks in advance.

/Lewis

Rob Sherwood <notifications@github.com<mailto:notifications@github.com>> 於 2016年4月12日 上午12:05 寫道：

Just to be clear -- did you figure out the problem here? If so, just for
tracking, what was it (even if it was just a local problem)?

- Rob
.

**Comment by capveg** [comment]
There are some things in the make system that get cached: perhaps try `make
rebuild` or `make versions` to see if that fixes the problem?  If it does
work, please let me know to see if there is something we can do about that.

Thanks,

- Rob
.

**Comment by jnealtowns** [comment]
The module manifest file does not get automatically updated when you
create|pull|merge a new code module into the tree. In this case the local
pull populated the new 7716 module, but it couldn't be compiled because its
base directory was not listed in the module manifest.

The manual way to resolve this problem is to remove $ONL/make/
module-manifest.mk. It will then get automatically rebuilt with the correct
settings for the local tree.

This problem happens enough that I will add a *githook* to remove the
module-manifest.mk on every merge.

**Comment by Lewis-Kang** [comment]
Yes, removing  $ONL/make/module-manifest.mk does solve this issue. Thanks Jeff and Rob.
