### ISSUE TITLE
BCM 56160 (Broadcom Hurricane 3) support

### ISSUE THREAD

**Issue by sweatypolarbears** [opencomputeproject/OpenNetworkLinux#644]
I wanted to ask whether Open Network Linux is supported by switches using Broadcom Hurricane 3 forwarding agent. I had checked the HCL and found that there is support for Hurricane 2.

**Comment by jnealtowns** [comment]
@sweatypolarbears Support for Hurricane3 platforms starts with a particular platform from a particular vendor and then that vendor supporting a particular forwarding agent. 

The best I can tell you is that ONIE appears to support the Edge-Core AS4620_54PE which claims to be based on Hurricane3. This box is not supported in ONL.
