### ISSUE TITLE
initrd unsquashfs is too old to support capabilities properly

### ISSUE THREAD

**Issue by sra-arrcus** [opencomputeproject/OpenNetworkLinux#645]
We're using ONL in "INSTALLED" mode (yeah, I know, not my decision), so proper installation depends on the copy of `unsquashfs` in the initrd.   We recently discovered that this (rather ancient) version of `unsquashfs` has a known bug that prevents it from restoring capabilities properly, which breaks things like recent versions of `ping`.   So we'd like to fix this.

This bug appears to have been fixed both in Debian and in the upstream `squashfs-tools`.  It would be awesome if ONL could update the initrd to follow one of these.  If needed, we can probably submit a pull request for this if somebody can point me at the right repository and branch to use as a starting point.

Thanks!

References:
* <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804194>
* <https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/unsquashfs.c>

**Comment by jnealtowns** [comment]
@sra-arrcus  I'll look into fixing this for you.

**Comment by jnealtowns** [comment]
The squashfs-tools have been updated to 4.4 as of daa6ab6. 
Please let me know if you see any issues. 

> loader# unsquashfs -v
unsquashfs version 4.4 (2019/08/29)
copyright (C) 2019 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
loader#
>
