### ISSUE TITLE
ONL doesn't see /dev/sda

### ISSUE THREAD

**Issue by nesselzzz** [opencomputeproject/OpenNetworkLinux#646]
I am trying to install ONL on my t1048-lb9 quanta switch. I am pretty new to this world and am still learning Linux. I have successfully installed ONIE on the switch and am trying to get ONL installed via ONIE however it ends with an error about not being able to find /dev/sda. Below are the logs. Any assistance anyone can provide would be very much appreciated. Thanks!

ONIE:/ # onie-nos-install http://opennetlinux.org/binaries/latest-DEB8-PPC-INSTA
LLED.installer
discover: Rescue mode detected. No discover stopped.
Info: Attempting http://opennetlinux.org/binaries/latest-DEB8-PPC-INSTALLED.installer ...
Connecting to opennetlinux.org (165.227.87.248:80)
installer            100% |*******************************|   136M  0:00:00 ETA
ONIE: Executing installer: http://opennetlinux.org/binaries/latest-DEB8-PPC-INSTALLED.installer
installer: computing checksum of original archive
installer: checksum is OK
installer: extracting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000112 seconds, 4.4MB/s
installer: copying file before resetting pad
installer: resetting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000090 seconds, 5.4MB/s
installer: extracting shar into /tmp/sfx-c5XsHl
installer: invoking installer installer.sh
Found installer tmpfs on /tmp/sfx-c5XsHl (/tmp) using opts rw,noatime
Resizing tmpfs /tmp to 1048576k
Unpacking ONL installer files...
Extracting from /tmp/sfx-c5XsHl/onie-installer.zip: onl-loader-fit.itb ...
Archive:  /tmp/sfx-c5XsHl/onie-installer.zip
  inflating: onl-loader-fit.itb
Extracting initrd to /tmp/sfx-c5XsHl/initrd-OeBDor
1+1 records in
1+1 records out
10607332 bytes (10.1MB) copied, 0.073677 seconds, 137.3MB/s
0+0 records in
0+0 records out
0 bytes (0B) copied, 0.000089 seconds, 0B/s
57580 blocks
gzip: corrupted data
Setting up /dev
Setting up /run
Setting up mounts
Launching ONL installer
Extracting from /tmp/sfx-c5XsHl/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-c5XsHl/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-c5XsHl/initrd-OeBDor
getting installer configuration
+ blkid
found ONIE MTD device /dev/mtd1
parsing FIT image in /dev/mtdblock1
default profile is quanta_lb9
retrieving ramdisk initramfs
reading initrd at [2a09e4:378ef4]
+ cat > /tmp/sfx-c5XsHl/initrd-ZwFeAy.img
extracting initrd /tmp/sfx-c5XsHl/initrd-ZwFeAy.img
+ /bin/mkdir /tmp/sfx-c5XsHl/chroot-xSchLG.d
+ xz -dc /tmp/sfx-c5XsHl/initrd-ZwFeAy.img | cpio -imd
4998 blocks
preparing chroot in /tmp/sfx-c5XsHl/chroot-xSchLG.d
+ mount -v -t proc proc /tmp/sfx-c5XsHl/chroot-xSchLG.d/proc
+ mount -v -t sysfs sysfs /tmp/sfx-c5XsHl/chroot-xSchLG.d/sys
+ modprobe -v efivarfs
+ mount -v -t devtmpfs devtmpfs /tmp/sfx-c5XsHl/chroot-xSchLG.d/dev
+ mount -v -t devpts devpts /tmp/sfx-c5XsHl/chroot-xSchLG.d/dev/pts
extracting initrd /tmp/sfx-c5XsHl/initrd-ZwFeAy.img
+ /bin/mkdir /tmp/sfx-c5XsHl/chroot-KTCuQw.d
+ xz -dc /tmp/sfx-c5XsHl/initrd-ZwFeAy.img | cpio -imd
4998 blocks
preparing chroot in /tmp/sfx-c5XsHl/chroot-KTCuQw.d
+ mount -v -t proc proc /tmp/sfx-c5XsHl/chroot-KTCuQw.d/proc
+ mount -v -t sysfs sysfs /tmp/sfx-c5XsHl/chroot-KTCuQw.d/sys
+ modprobe -v efivarfs
+ mount -v -t devtmpfs devtmpfs /tmp/sfx-c5XsHl/chroot-KTCuQw.d/dev
+ mount -v -t devpts devpts /tmp/sfx-c5XsHl/chroot-KTCuQw.d/dev/pts
+ chroot /tmp/sfx-c5XsHl/chroot-KTCuQw.d /bin/sh -c IFS=;onie-sysinfo -h
un-mounting mounts points in chroot /tmp/sfx-c5XsHl/chroot-KTCuQw.d
+ umount -v /tmp/sfx-c5XsHl/chroot-KTCuQw.d/sys
+ umount -v /tmp/sfx-c5XsHl/chroot-KTCuQw.d/proc
+ umount -v /tmp/sfx-c5XsHl/chroot-KTCuQw.d/dev/pts
+ umount -v /tmp/sfx-c5XsHl/chroot-KTCuQw.d/dev
cleaning up chroot in /tmp/sfx-c5XsHl/chroot-KTCuQw.d
+ /bin/rm -fr /tmp/sfx-c5XsHl/chroot-KTCuQw.d
+ /bin/rm /tmp/sfx-c5XsHl/initrd-ZwFeAy.img
un-mounting mounts points in chroot /tmp/sfx-c5XsHl/chroot-xSchLG.d
+ umount -v /tmp/sfx-c5XsHl/chroot-xSchLG.d/sys
+ umount -v /tmp/sfx-c5XsHl/chroot-xSchLG.d/proc
+ umount -v /tmp/sfx-c5XsHl/chroot-xSchLG.d/dev/pts
+ umount -v /tmp/sfx-c5XsHl/chroot-xSchLG.d/dev
cleaning up chroot in /tmp/sfx-c5XsHl/chroot-xSchLG.d
+ /bin/rm -fr /tmp/sfx-c5XsHl/chroot-xSchLG.d
ONL Installer Open Network Linux OS ONL-master, 2019-07-23.01:53-01d1564
ONL installer running chrooted.
Detected platform powerpc-quanta-lb9-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
installer failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 212, in runLocalOrChroot
    code = self.installer.run()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1327, in run
    return self.installUboot()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1212, in installUboot
    st = os.stat(self.device)
OSError: [Errno 2] No such file or directory: '/dev/sda'
re-attaching to tty
entering Python debugger (installer_debug=1)
> /usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py(1212)installUboot()
-> st = os.stat(self.device)
(Pdb)

**Comment by jnealtowns** [comment]
@nesselzzz The LB9 has a removable compact flash for /dev/sda. Its possible yours is missing or damaged. 

UBoot should report if the card is present at boot:

> In:    serial
Out:   serial
Err:   serial
Net:   TSEC0: PHY is Broadcom BCM5461S (2060c1)
TSEC0
IDE:   Bus 0: OK
  Device 0: Model: CF CARD Firm: Ver7.01K Ser#: 5B3B06B30004EE7C
            Type: Removable Hard Disk
            Capacity: 3811.9 MB = 3.7 GB (7806960 x 512)
Hit any key to stop autoboot:  0
=>

**Comment by nesselzzz** [comment]
I can’t believe that I missed that. You’re absolutely right. Do you know what kind of CF The switch usually takes?

**Comment by sonoble** [comment]
Here are someone's notes about CF cards and issues you can run into, you would probably want a >= 2G one for ONL

http://reumann-snippets.blogspot.com/2015/01/upgrade-quanta-lb9-for-pica-os-24-or.html

**Comment by nesselzzz** [comment]
You guys are awesome! Thank you for your help. I ordered a few different CF cards all under 120 Mb/s. They get in tomorrow, so I’ll put them in and give it another go and let you know how it goes. Thanks again!

**Comment by jnealtowns** [comment]
@nesselzzz  I hope it worked out!

**Comment by nesselzzz** [comment]
Yes, it did. I just installed the CF card yesterday, and was successfully able to install ONL. Thank you all for your guidance!
