### ISSUE TITLE
Variable ONLPDUMP should be changed

### ISSUE THREAD

**Issue by CommitThis** [opencomputeproject/OpenNetworkLinux#658]
https://github.com/opencomputeproject/OpenNetworkLinux/blob/8b6816bc3f649c85476e6566c809bbddbf0c81d4/packages/base/all/vendor-config-onl/src/python/onl/platform/baseconfig.py#L63

I don't understand too well how ONL is built and whether this is an issue, but, the mentioned line sets the ONLPDUMP variable to `onlpdump` and it is my understanding that this file has changed name to `onlps`? If this is so then `onie-info.json` and `platform-info.json` will not be created.

**Comment by jnealtowns** [comment]
The binary build has been changed to onlps (staged to match the ONLPv2 implementation) but the actual package still installs the binary as onlpdump. Please see:
https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/base/any/templates/onlp-platform-revision.yml#L26

**Comment by CommitThis** [comment]
Sorry @jnealtowns, turns out I had modified the onlp package yaml and forgot about it!
