### ISSUE TITLE
Jessie: Boot.d scripts not being run

### ISSUE THREAD

**Issue by CommitThis** [opencomputeproject/OpenNetworkLinux#659]
We are sadly running on Jessie (i'd like to get to at least Stretch) and I noticed that the `boot.d` scripts were not being run. I'm not 100% certain of how the boot process works but I've outlined below what I think may be an issue.

I noticed that in (Stretch and Buster) the boot scripts were being run by an overlay of `/sbin/init` (or `inittab` in the case of sysvinit) which runs the scripts then passes control to systemd. I tried to copy this pattern for Jessie, by creating my own `init` script, and still had no luck. I then found that `switchroot` calls systemd directly (after a positive test for `/lib/systemd/systemd` being executable), bypassing `init` and therefore the boot scripts were not being run. 

https://github.com/opencomputeproject/OpenNetworkLinux/blob/8b6816bc3f649c85476e6566c809bbddbf0c81d4/packages/base/all/initrds/loader-initrd-files/src/bin/switchroot#L65-L66

Additionally, it seems that in Stretch and Buster, `/lib/systemd/systemd` does not exist -- this test fails so `switchroot` calls `init` instead of systemd which would explain why the boot.d scripts run on those OSs.

**Comment by jnealtowns** [comment]
@CommitThis Selecting systemd under the Jessie build is not something we support but it won't be hard to fix for you. The systemd vs sysvinit overlays that accomplish the boot sequence are only provided for stretch and buster. 

The mechanism when running systemd is to provide an overlay /sbin/init script which performs the boot.d sequence and then execs systemd:

https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/builds/any/rootfs/stretch/systemd/overlay/sbin/init

If you give me some time I'll add systemd support to the Jessie build.

**Comment by CommitThis** [comment]
Thankyou!

**Comment by lxu4net** [comment]
I think I have same case. 
I built a ONL OS8 with INIT=systemd, then I found the switch chip didn't init.

**Comment by CommitThis** [comment]
@lxu4net I got it to work by replacing line 66 as mentioned above with
```
elif [ -x /newroot/lib/systemd/systemd ]; then 
    exec switch_root -c /dev/console /newroot /sbin/init`
```

and adding the following file 

```
#!/bin/bash
/etc/boot.d/boot

echo "Starting systemd..."
exec /lib/systemd/systemd
```
to a jessie overlay at `builds/any/rootfs/jessie/common/overlay/sbin/init`, which is the same pattern used elsewhere.

Caveat: I don't know if this has any side effects. 

Given my previous comment on `systemd` not being found: I was looking at it's location in the base docker images for debian; apparently it's is not installed. I haven't spent much time on `stretch` and `buster` because we need `jessie` to run the Barefoot P4 SDE for Tofino chips -- consequently I can't really tell if they're executed at all in the later OSs. If they are, presumably whatever method that uses would be preferable to intercepting init.

**Comment by lxu4net** [comment]
I just copy them from builds/any/rootfs/stretch. Lucky it's worked for me.
