### ISSUE TITLE
Kernel problem with OFDPA and ONL

### ISSUE THREAD

**Issue by lucascarrafa** [opencomputeproject/OpenNetworkLinux#674]
Hi,

I am facing problems when running OFDPA at ONL. The terminal displays the following message:

-----------------------------------------------------------------------------------------------------------
root@localhost:~# service ofagentd start
Starting ofagentd.
root@localhost:~# Setting up OFDPA running environment
insmod: ERROR: could not load module /lib/modules/4.14.109-OpenNetworkLinux-armel/ofdpa/linux-kernel-bde.ko: No such file or directory
insmod: ERROR: could not load module /lib/modules/4.14.109-OpenNetworkLinux-armel/ofdpa/linux-user-bde.ko: No such file or directory
mknod: invalid major device number ‘’
mknod: invalid major device number ‘’
ofagentapp[3807]: Start command = ofagentapp -i b86a97aa7580
Jan 01 00:50:32.432 ofagent: MSG: version 3.0.5.5 -- Built on Thu Jan 31 2019 at 01:16:16 UTC
OF Datapath ID: 0x0000B86A97AA7580
Jan 01 00:50:32.432 ofstatemanager: INFO: Changing switch DPID to 0000b86a97aa7580
Initializing the system.
insmod: ERROR: could not load module linux-kernel-bde.ko: No such file or directory
insmod: ERROR: could not load module linux-user-bde.ko: No such file or directory
open /dev/linux-user-bde: : No such file or directory
sdkCustomInit: ERROR: PCI SOC device probe failed
systemMappingInit: Error initializing driver, rc = -1.

Failure calling ofdpaClientInitialize(). rc = -27
ofagentapp[3814]: Received terminate signal

-----------------------------------------------------------------------------------------------------------

Software:
Linux localhost 4.14.109-OpenNetworkLinux-armel #1 SMP PREEMPT Tue Jul 23 03:29:23 UTC 2019 armv7l
latest-DEB8-ARMEL-INSTALLED.installer              24-Jul-2019 16:32        
latest-DEB8-ARMEL-SWI.installer                    24-Jul-2019 16:31
ofdpa_3.0.5.5 accton2.7~3-1_armel.deb 

Hardware:
Edge-core AS4610-54T (B)

I tried to find an ONL image with kernel 3.16, but the official website has only kernel 4.14

can anybody help me?

**Comment by lucascarrafa** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/opennetworklinux/cbuVquwWVYA/VPxj0WfpEQAJ

**Comment by paulmenzel** [comment]
Sorry for following up here, but where can I get the OF-DPA driver? The URL https://support.edge-core.com/hc/article_attachments/360028460854/ofdpa_3.0.5.5_accton2.7_3-1_armel.deb does not work, and the Edgecore support replied:

> I am sorry to inform you that we does not maintain OF-DPA anymore.
> Therefore, If you're interested in this technology and have a need, please contact with Broadcom directly.
