### ISSUE TITLE
Can someone please sign the http://apt.opennetlinux.org/debian repo 

### ISSUE THREAD

**Issue by irinetDevOpps** [opencomputeproject/OpenNetworkLinux#689]
Reading package lists... Done
W: The repository 'http://apt.opennetlinux.org/debian unstable Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by aep** [comment]
how was this resolved?
