### ISSUE TITLE
errors: couldn't mount because of unsupported optional features, no 'ma1' , onlpdump

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#69]
I 'git clone' and 'make docker' on 4/14 and build ONIE installer successfully.

**During ONIE NOS installation, it has the following error (tested on AS7716-32X):**

Installing boot files...
Installing boot-config...
EXT3-fs (sdb4): error: **couldn't mount because of unsupported optional features (240)**
EXT2-fs (sdb4): error: couldn't mount because of unsupported optional features (240)
Installing Open Network Linux Software Image (ONL-2.0.0_ONL-OS_2016-04-14.1034-d79158c_AMD64.swi)...
EXT3-fs (sdb6): error: couldn't mount because of unsupported optional features (240)
EXT2-fs (sdb6): error: couldn't mount because of unsupported optional features (240)

**After installation, reboot to run NOS. It has the following issue:**
**1. Device "ma1" does not exist:**
[ Starting Autoboot ]
[ Configuring Interfaces ]
/bin/ifup: line 76: can't create /proc/sys/net/ipv6/conf/ma1/autoconf: nonexistent directory
udhcpc: SIOCGIFINDEX: No such device
grep: /sys/class/net/ma1/operstate: No such file or directory
ifconfig: SIOCGIFFLAGS: No such device
Device "ma1" does not exist.

**2. errors while running onlpdump:**
SFPs:
01-01 00:10:49.296209 [x86_64_accton_as7716_32x] Unable to open the sfp_is_present_all device file.
  Presence Bitmap: Error: E_INTERNAL
  RX_LOS Bitmap: None

01-01 00:10:49.296285 [x86_64_accton_as7716_32x] Unable to read present status from port(0)

**Comment by sonoble** [comment]
Hi Lewis:

EXT3-fs (sdb4): error: couldn't mount because of unsupported optional features (240)
EXT2-fs (sdb4): error: couldn't mount because of unsupported optional features (240)
Installing Open Network Linux Software Image (ONL-2.0.0_ONL-OS_2016-04-14.1034-d79158c_AMD64.swi)...
EXT3-fs (sdb6): error: couldn't mount because of unsupported optional features (240)
EXT2-fs (sdb6): error: couldn't mount because of unsupported optional features (240)

Are known and should not cause issues.

As for the other issues we have not done much testing with the 7716 yet, have you run previous builds?

**Comment by sonoble** [comment]
@Lewis-Kang 
I don't believe the ethernet mapping is correct:

https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/accton/x86-64/x86-64-accton-as7716-32x/platform-config/r0/src/lib/boot/x86-64-accton-as7716-32x-r0

root@localhost:~# more /etc/onl/net
pci0000:00/0000:00:14.0 ma1
root@localhost:~# ifconfig |grep eth
eth0      Link encap:Ethernet  HWaddr cc:37:ab:81:be:4f
eth1      Link encap:Ethernet  HWaddr 00:10:18:00:00:00

05:00.0 Ethernet controller: Intel Corporation Device 15ab
05:00.1 Ethernet controller: Intel Corporation Device 15ab

if I look at the 5712 it has 

00:14.0 Ethernet controller: Intel Corporation Device 1f41 (rev 03)

I will submit a pull request to update it

**Comment by Lewis-Kang** [comment]
Hi Steven, 

The installer in https://www.opennetlinux.org/binaries which was built on March 1st. It doesn't have 7716 ported fron ONL1.0 yet. So, I don't have previous version to compare with. 

Thanks.

/Lewis
P.S. AS7716 was ported from ONL1.0 to ONL2.0 on March 24th by this commit: https://github.com/opencomputeproject/OpenNetworkLinux/commit/7a0d29ddc4ae1b26710bb414a306e631ff4eaec6

**Comment by sonoble** [comment]
Hi Lewis,

I wasn't sure if you had built a more recent version.  I have updated the code and am going to test my changes.

**Comment by sonoble** [comment]
Hi Lewis,

My changes did not work

root@localhost:~# cat /etc/onl/net
pci0000:00/0000:05:00.0 ma1
root@localhost:~# ifconfig |grep eth
eth0      Link encap:Ethernet  HWaddr cc:37:ab:81:be:4f
eth1      Link encap:Ethernet  HWaddr 00:10:18:00:00:00

I will continue digging.

**Comment by Lewis-Kang** [comment]
Hi Steven,

Thanks.

The installer I built last night has the file name
 ONL-2.0.0_ONL-OS_2016-04-14.1034-d79158c_AMD64_INSTALLER 

which matches the latest commit:
https://github.com/opencomputeproject/OpenNetworkLinux/commit/d79158cdcfdf4307b8a5299bf15a972de7fc31fe

So, it should be the newest version so far.

**Comment by sonoble** [comment]
I get the feeling that we need @brandonchuang to look at the code as I see the same issue, it seems things are not mapping correctly.  I booted the last ONL 1.0 image http://opennetlinux.org/binaries/2016.01.04.21.46.18cc76084b3104961117aa8434599c8c67a9a276/onl-18cc760-amd64-all.2016.01.04.21.36.installer and it also fails to map the ethernet ports.

**Comment by jnealtowns** [comment]
The sysfs path for eth0 is wrong in the 7716 platform config.

I've fixed it in this commit:
https://github.com/opencomputeproject/OpenNetworkLinux/commit/b6c1996aa0fb7df2325b39acaf97d3654f0a44c1

While eth0 is now correctly renamed to ma1 I was unable to make eth0/ma1
link up with the latest ONL build.

**Comment by Lewis-Kang** [comment]
Because management port is functioning well under ONIE environment, I asked David who developed ONIE for AS7716-32X. He told me a special kernel driver patch is needed to solve this issue and he had given the patch files to Brandon. I talked with Brandon yesterday, we need to come out a solution to avoid the kernel driver patch from malfunctioning other platforms if they are using the same Broadcom's MAC but with different HW design for management port. I think we need to let certain patch code to be executed only when running on AS7716 platform. I am waiting for opinions on this from other colleagues. Do you have any suggestion on identifying the device is AS7716 in kernel? Is checking the EEPROM content the only way for it?

Thanks.

/Lewis Kang

Jeffrey Townsend <notifications@github.com<mailto:notifications@github.com>> 於 2016年4月15日 下午11:55 寫道：

The sysfs path for eth0 is wrong in the 7716 platform config.

I've fixed it in this commit:
https://github.com/opencomputeproject/OpenNetworkLinux/commit/b6c1996aa0fb7df2325b39acaf97d3654f0a44c1

While eth0 is now correctly renamed to ma1 I was unable to make eth0/ma1
link up with the latest ONL build.

**Comment by Lewis-Kang** [comment]
@jnealtowns @sonoble , I just emailed you our patch for ma1 issue for your reference.
The mgmt-port-init-config.patch is specific for AS7716, so I think it should be enclosed (after applying the patch) by a condition check for execution only on AS7716 to avoid affecting other platform (this is yet to be done).

**Comment by sonoble** [comment]
I am building the kernel now and will confirm if this patch works.

**Comment by sonoble** [comment]
The patch works:

ma1       Link encap:Ethernet  HWaddr cc:37:ab:81:be:4f
          inet addr:10.6.100.112  Bcast:10.7.255.255  Mask:255.254.0.0
          inet6 addr: fe80::ce37:abff:fe81:be4f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:115 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:13322 (13.0 KiB)  TX bytes:2104 (2.0 KiB)
          Interrupt:16

root@localhost:~# uname -a
Linux localhost 3.2.65-1+deb7u2-OpenNetworkLinux #1 SMP Sat Apr 16 01:45:56 UTC 2016 x86_64 GNU/Linux
root@localhost:~# cat /etc/onl/platform
x86-64-accton-as7716-32x-r0

**Comment by Lewis-Kang** [comment]
Steven, thanks.

/Lewis Kang

Steven Noble <notifications@github.com<mailto:notifications@github.com>> 於 2016年4月16日 上午9:51 寫道：


The patch works:

ma1 Link encap:Ethernet HWaddr cc:37[:ab:]81:be:4f
inet addr:10.6.100.112 Bcast:10.7.255.255 Mask:255.254.0.0
inet6 addr: fe80::ce37:abff:fe81:be4f/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:115 errors:0 dropped:0 overruns:0 frame:0
TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:13322 (13.0 KiB) TX bytes:2104 (2.0 KiB)
Interrupt:16

root@localhost:~# uname -a
Linux localhost 3.2.65-1+deb7u2-OpenNetworkLinux #1<https://github.com/opencomputeproject/OpenNetworkLinux/pull/1> SMP Sat Apr 16 01:45:56 UTC 2016 x86_64 GNU/Linux
root@localhost:~# cat /etc/onl/platform
x86-64-accton-as7716-32x-r0

**Comment by Lewis-Kang** [comment]
ma1 linkup issue and onlpdump issue can be fixed by https://github.com/opencomputeproject/OpenNetworkLinux/pull/72
