### ISSUE TITLE
set module as loadable during ONL build

### ISSUE THREAD

**Issue by frederic-loui** [opencomputeproject/OpenNetworkLinux#698]
Hi,
I'm sorry if this is a "dumb" question, but i could not find a suitable answer.
I compiled ONL 9 successfully and I'm not sure why `ixgbe` driver is failing to work properly. 
(Error code: ... CS4227 reset failed: -18)

After a few check, I notice that ixgbe driver is built-in ONL.

Therefore, I would like to recompile ONL 9 with ixgbe as a loadable module.
There is a `.config` file that we can alter but I was wondering if in ONL build process you had a recommended to achieve this ? (Makefile target, patch at a specific folder etc.)

The objective would be to look at the log during load/unload menu.

In case we need to apply a patch to the kernel module, do you have a recommeded method tied to ONL build ?

Sorry again if this question has been already answered. 
(I'd glad to have the pointer to that topic then :))

Thanks for your feedback !
Frederic LOUI

**Comment by tsihang** [comment]
I am facing same question.
Could any one help us ?

Many thanks

**Comment by sonoble** [comment]
Hello,
The configuration for the kernels is under packages/base/any/kernels/(kernel name) /configs/$arch/$arch.config for example https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/base/any/kernels/4.19-lts/configs/x86_64-all/x86_64-all.config.

You can enable the driver as a module there.

**Comment by tsihang** [comment]
Many thanks

**Comment by frederic-loui** [comment]
I found the folder you mentioned a week ago, but wasn't sure it was the ONL
official way to do this.
For what is worth, I recompiled the kernel and confirm it works as expected.

The module is now loadable/unloadable.

Thanks !
Frederic LOUI

Le mar. 24 mars 2020 à 05:56, Steven Noble <notifications@github.com> a
écrit :

**Comment by sonoble** [comment]
Hi,

Make sure that you copy the .config file back to the x86_64-all.config from the kernel build location as the Linux build system will do some minor changes to the config when you build it.

**Comment by tsihang** [comment]
Many thanks @sonoble
