### ISSUE TITLE
Building for specific platform

### ISSUE THREAD

**Issue by EricZaluzec** [opencomputeproject/OpenNetworkLinux#699]
I'm following the [build doc](https://opennetlinux.org/doc-building.html) to build ONL installer binary with docker. I've read the docs on github, onl website, and 3rd party sites; sorry if I overlooked this question. I'd like to build ONL specifically for the [as4630-54pe](https://github.com/opencomputeproject/OpenNetworkLinux/tree/master/packages/platforms/accton/x86-64/as4630-54pe) platform.

Do I need to pass in any platform arguments/options to build for this specific platform? If not, is there a specific platform output directory that I can find the installer for this specific platform? Thank you.

**Comment by dracuka** [comment]
https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/docs/SupportedHardware.md  
it seems that this HW is not supported.

**Comment by EricZaluzec** [comment]
Thanks @dracuka. So devices on the SupportedHardware page that show `YES` in the `In Lab` column are devices that have been tested and verified to work in lab? I'm looking for a 48x1G switch port where I don't have to do much low level embedded / kernel driver development on the Ethernet port switches out of the box.
