### ISSUE TITLE
How to build a custom package (deb) from our own source files ?

### ISSUE THREAD

**Issue by tsihang** [opencomputeproject/OpenNetworkLinux#704]
Hi, 
I have packages must be built locally due to some legal issues. I have two question about customing:
1) How involve the needed packages into ONL building scripts or rootfs ?
2) Is there a way to build build an external (private) debian package from own source files ?
3) If above not support, is there a way to add private apt sources maintained by our own ?   

Thanks

**Comment by laiguoliang-lyr** [comment]
You can put your package in this path "OpenNetworkLinux/REPO/jessie/packages/binary-amd64/"and then add your package name in "$OpenNetworkLinux/builds/any/rootfs/jessie/common/*.yml"

**Comment by tsihang** [comment]
Hi @laiguoliang-lyr 
Thanks for your great help.
It works
