### ISSUE TITLE
Is it possible to build an arm64 INSTALLER on an non-arm64 host ?

### ISSUE THREAD

**Issue by tsihang** [opencomputeproject/OpenNetworkLinux#705]
Hi,
We are hoping for an ARM64 installer. Is it possible to build the INSTALLER on an non-arm64 host ? What I mean is that whether the ONL supports cross compile or not.

Thanks

**Comment by sonoble** [comment]
Yes it will cross compile for arm64.  If you run the full build it will build arm64 versions for the NXP RDB systems.

**Comment by tsihang** [comment]
What I know so far is that the ONL always be built in docker. Is it possible to map the cross toolchain in docker ?

**Comment by sonoble** [comment]
The cross toolchains are already included in the docker images.  I am not sure I understand your question.

**Comment by tsihang** [comment]
Yes, exactly.
Thanks a lot.
