### ISSUE TITLE
How to choose the linux kernel version in jessie build

### ISSUE THREAD

**Issue by sharathkurudi** [opencomputeproject/OpenNetworkLinux#714]
When I build ONL the default kernel version chosen for jessie is 4.19, I would like to choose the 4.14 kernel version for my build, could anyone advice on how to do that?

**Comment by tsihang** [comment]
$ONL/packages/platforms/<your-company>/<your-arch>/<your-platform>/platform-config/r0/src/lib/<your-arch>-<your-company>-<your-platform>-r0.yml

**Comment by sharathkurudi** [comment]
Thanks a lot. I figured it
