### ISSUE TITLE
How to update grub after anything changes in /etc/default/grub

### ISSUE THREAD

**Issue by tsihang** [opencomputeproject/OpenNetworkLinux#720]
Hi,
I want to change kernel parameters through GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub.
After edit, I execute update-grub and reboot.
But those changes never appear in /boot/grub/grub.cfg

Is there any thing wrong ? What should I do ?

Thanks

**Comment by abhiranjeet** [comment]
Hi @tsihang 
Were you able to resolve this issue ?

**Comment by tsihang** [comment]
> Hi @tsihang Were you able to resolve this issue ?

Yes, I think I have resolved it by following steps:

1. Edit platform configure file.
$ vi $ONL/packages/platforms/$COMPANY/$ARCH/$PLATFORM/platform-config/r0/src/lib/$ARCH-$COMPANY-$PLATFORM-r0.yml
...
**args: >-**
console=ttyS0,115200n8
...
2. Rewrite section specified by **args**. Here is an example that I changed this section like below.
**console=ttyS0,115200n8  iommu=pt intel_iommu=on pcie_aspm=off pci=noaer**
3. Save and recompile ONL

Wish this help you.

**Comment by tsihang** [comment]
> Hi @tsihang Were you able to resolve this issue ?

**Comment by abhiranjeet** [comment]
Hi @tsihang 

Yes, it helped. I am able to change my kernel version.

But there is a different problem I am facing with that. 

I am installing ONL on Accton AS7712-32X switch. By default the kernel version was set to 4.14, and I changed it to 4.9. But after changing the kernel version, I don't see the modules which were loaded previously when kernel was 4.14. Refer below output :

```

Kernel Version = 4.14

root@localhost:~# lsmod
Module                  Size  Used by
gpio_ich               16384  0
x86_64_accton_as7712_32x_leds    16384  0
x86_64_accton_as7712_32x_psu    16384  0
x86_64_accton_as7712_32x_cpld1    16384  2 x86_64_accton_as7712_32x_leds,x86_64_accton_as7712_32x_psu
x86_64_accton_as7712_32x_fan    16384  0
accton_i2c_cpld        20480  3 x86_64_accton_as7712_32x_fan,x86_64_accton_as7712_32x_leds,x86_64_accton_as7712_32x_psu
ym2651y                16384  0
optoe                  20480  0
```

After making the change, this is what I see :  
```

Kernel Version = 4.9

root@localhost:~# lsmod
Module                  Size  Used by
at24                    7104  0
ym2651y                 8027  0
optoe                   6867  0
```

I even tried to modprobe them manually, this is error I get : 
```
root@localhost:~# sudo modprobe x86_64_accton_as7712_32x_leds
modprobe: FATAL: Module x86_64_accton_as7712_32x_leds not found in directory /lib/modules/4.9.75-OpenNetworkLinux
```

Will I loose those modules if I change kernel version by changing in that $ARCH-$COMPANY-$PLATFORM-r0.yml file ?
