### ISSUE TITLE
This project's future?

### ISSUE THREAD

**Issue by edrozenberg** [opencomputeproject/OpenNetworkLinux#781]
Curious if this project is still considered active and promising for the future. The hardware compatibility list https://opennetlinux.org/hcl.html is not updated since July 2019, Debian references are to v7 and v8 (Debian stable is now at v10) and there is little activity in the issues.

Trying to decide where to start with open networking for my Edge-Core/Accton switch coming soon, and it looks like Microsoft's SONiC is more active.

**Comment by paulmenzel** [comment]
I am having the same question. What route did you go?

**Comment by edrozenberg** [comment]
I'm planning to start testing with https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms on a couple of Super Micro SSE-G3648B (aka OEM Celestica E1031). 

Cumulus (commercial, now owned by Nvidia) has been a popular option for some years.

Other network software mentioned on Edge Core site (some for DC, some for packet optical) many of which are commercial/not open (I see they've removed all mentions of Cumulus for some reason).
ADVA - Ensemble Activator
Arrcus - ArcOS
CapGemini - SDvAS
CapGemini- Altran
CGS - COS
Cisco - IOS-XR
DriveNets - DNOS
Exware - ExaNOS
Inﬁnera - CNOS
IP Infusion - OcNOS
Ixia - Vision Edge OS
Kaloom - Cloud Edge Fabric™
Netscout - Packet Flow Switch
Noviflow - NoviWare
Pica8 - PicOS
Pluribus Networks - Netvisor® OS (ONVL)
Radisys - SD-PON
Microsoft - SONiC
Linux Foundation - OpenSwitch
Open Compute Project - Open Network Linux
Volta Networks
