### ISSUE TITLE
arm64 kernel modules installation

### ISSUE THREAD

**Issue by sergiolopesmarques** [opencomputeproject/OpenNetworkLinux#816]
I’m able to generate the version 9 release (stretch) and install it via ONIE in my equipment that uses a ls1023a processor from NXP.
Don't know why but kernel modules that results from kernel compilation are not being installed at /lib/modules/4.9.75. I believe that ls1043ardb, ls1046ardb, ls1088ardb, ls2088ardb boards should have the same problem…
Only a small kernel module that I had to write, dued to our hardware design, appears at /lib/modules/4.9.75.
What could be wrong?
Any help would be greatly appreciated

**Comment by sergiolopesmarques** [comment]
I've already figure it out the way to solve this issue.
Thanks anyway

**Comment by paulmenzel** [comment]
I guess this was related to your message [*https://groups.google.com/g/opennetworklinux/c/C1FhpV7FH20*][1] to the ONL mailing list?

I am sorry, you did not get any reply. The project looks quite inactive in that regard.

Could you please document, how you solved the issue?

[1]: https://groups.google.com/g/opennetworklinux/c/C1FhpV7FH20

**Comment by sergiolopesmarques** [comment]
Hi Paul,

Below you can see the small change I made to solve my issue.
Basically I have made a new package with the kernel modules folder and then I added it in my switch kernel module package depends list.
Is it correct?

diff --git a/packages/base/arm64/kernels/kernel-4.9-lts-arm64-all/PKG.yml b/packages/base/arm64/kernels/kernel-4.9-lts-arm64-all/PKG.yml
index a22e994f..eede539e 100644
--- a/packages/base/arm64/kernels/kernel-4.9-lts-arm64-all/PKG.yml
+++ b/packages/base/arm64/kernels/kernel-4.9-lts-arm64-all/PKG.yml
@@ -15,5 +15,14 @@ packages:
       builds/kernel-4.9* : $$PKG_INSTALL/
       builds/linux-4.9*-mbuild : $$PKG_INSTALL/mbuilds
       builds/linux-4.9*-dtbs : $$PKG_INSTALL/dtbs
+    changelog:  Change changes changes.,
+
+  - name: onl-kernel-4.9-lts-arm64-all-modules
+    version: 1.0.0
+    summary: Open Network Linux Kernel 4.9 Modules for ARM64 Platforms
+
+    files:
+      builds/lib : /lib

     changelog:  Change changes changes.,
+
diff --git a/packages/platforms/alb/arm64/t2t0/modules/PKG.yml b/packages/platforms/alb/arm64/t2t0/modules/PKG.yml
new file mode 100644
index 00000000..ca425599
--- /dev/null
+++ b/packages/platforms/alb/arm64/t2t0/modules/PKG.yml
@@ -0,0 +1,21 @@
+prerequisites:
+  packages:
+    - onl-kernel-4.9-lts-arm64-all:arm64
+    - onl-kernel-4.9-lts-arm64-all-modules:arm64
+    - onl-vendor-alb-modules:arm64
+
+packages:
+  - name: onl-platform-modules-arm64-olt2t0
+    version: 1.0.0
+    arch: arm64
+    copyright: Copyright 2013, 2014, 2015 Big Switch Networks
+    maintainer: support@bigswitch.com
+    support: opennetworklinux@googlegroups.com
+    summary: ONL Platform Modules Package for the arm64-olt2t0
+    depends: [ onl-vendor-alb-modules, onl-kernel-4.9-lts-arm64-all-modules ]
+
+    files:
+      builds/lib: /lib
+      builds/etc: /etc
+
+    changelog: Changes
