### ISSUE TITLE
Build ONL with export VERSION=10

### ISSUE THREAD

**Issue by abhiranjeet** [opencomputeproject/OpenNetworkLinux#856]
Hi all,

I am trying to build ONL by using this variable before `make docker`
`export VERSION=10`

It seems to work for 8 & 9, but 10 gives following errors
```
Pulling opennetworklinux/builder10:1.2...
done.
/bin/sh: 1: /etc/init.d/apt-cacher-ng: not found
CRITICAL:docker_shell:The apt-cacher-ng service could not be started.
Makefile:56: recipe for target 'docker' failed
make: *** [docker] Error 1
```

Any suggestions ?

**Comment by paulmenzel** [comment]
Debian 10 is currently not support. Despite merge/pull requests being helpful, it probably wouldn’t be reviewed or submitted, as the state of Open Network Linux is currently undetermined.

**Comment by sonoble** [comment]
I will be giving a talk at OCP about restarting the ONL project directly under OCP instead of as part of BSN/Arista.  I have administrator privileges but I have not used them as we need to talk about the project in general and put together a team to review all of the outstanding pull requests.

**Comment by abhiranjeet** [comment]
Great! 

Just a followup to this query, I have seen that ONL build process involves using onlbuilder image pulled from docker hub. However, is there a containerized version of ONL available instead of the builder ?

**Comment by abhiranjeet** [comment]
Additionally, is there a Dockerfile in the repo for onlbuilder image which gets pulled from the docker hub
