### ISSUE TITLE
Build ONL for a specific switch model

### ISSUE THREAD

**Issue by abhiranjeet** [opencomputeproject/OpenNetworkLinux#865]
Hi,

I have seen that we can build ONL for a specific vendor by making changes in `ONLPM_OPTION_PLATFORM_WHITELIST` variable in setup.env file. However, I don't see that variable in master branch. How can I do the same in master branch ? Is there any other variable ?

Thanks !

**Comment by sonoble** [comment]
Hi Abhinav,

We do that in the dent project if you want another example. Stratum uses it
to separate out onlpv2 and we use it to specify switch es that are directly
supported in dent.

**Comment by abhiranjeet** [comment]
Hi @sonoble,

Thanks for the reference to DentOS, I can see this option in setup.env file of its repository :
```
# Build Whitelist
export ONLPM_OPTION_PLATFORM_ALLOWLIST="\
arm-accton-as4610-54-r0
arm64-nxp-ls1043ardb-r0
arm64-nxp-ls1046ardb-r0
arm64-delta-tx4810-r0
arm64-delta-tn4810m-r0
arm64-delta-tn48m2-r0
arm64-delta-tn48m-r0
arm64-delta-tn48m-poe-r0
arm64-delta-tn48m-dn-r0
arm64-delta-tn48m-poe-dn-r0
arm64-delta-tn4810m-dn-r0
arm64-wnc-qsd61-aom-a-48-r0
arm64-wnc-qsa72-aom-a-48p-r0
arm64-accton-as4224-52p-r0
arm64-accton-as4224-52t-r0
arm64-accton-as5114-48x-r0
arm64-accton-as4564-26p-r0
x86-64-accton-as5912-54x-r0
x86-64-kvm-x86-64-r0
x86-64-mlnx-msn2410-r0
"
```

I want to build this for as7712-32x, so I should add a line `x86-64-accton-as7712-32x-r0`
Does DentOS support this switch ?

**Comment by sonoble** [comment]
Hi,

You want to take the modifications to onlpm.py to support the allowlist and
add them into your version of onl:

https://github.com/dentproject/dentOS/commit/2bd5b55f239592506ef39c764570d75c549f5e2e#diff-4b830138a4ed9e4e7b21d19f247b36937ad54840df3f87a6b05a604edd5b7307L1217

Then you can add the allowlist to setup.env and set the device you want to
build.

If you specifically want to build dentos for a use case then yes you can
just add the device to the list and remove any devices you don't want.

**Comment by abhiranjeet** [comment]
Hi,

For Accton AS7712-32X, simply adding that model and commenting out the other should do the job ?
I will try this and let you know.

Thanks !

**Comment by abhiranjeet** [comment]
Hi @sonoble ,

Thanks for the tip. I am able to build it for AS7712-32X now. 

There still remains one issue : Resulting images that get built, have Debian 8 & Debian 9 as their Base OS. Build fails for Debian 10. This is happening irrespective of what changes I make "PLATFORM WHITELIST" option. Is DentOS not supporting Debian 10 ?

**Comment by sonoble** [comment]
This is something we need to work on for any os using the onl build system.
The initial Debian 10 based onlbuilder was never finished.

 We should probably focus on Debian 11 and skip 10 unless there is a real
need.

I have this on my list of things to focus on once we have the team in place
to work through some of the biggest issues.

**Comment by abhiranjeet** [comment]
Thanks for the clarity @sonoble !
