### ISSUE TITLE
Some error about apt update in ONL

### ISSUE THREAD

**Issue by linhil** [opencomputeproject/OpenNetworkLinux#887]
![image](https://user-images.githubusercontent.com/76023357/167997800-9d6e920a-03ce-4f02-8d94-fe897b4a9a86.png)
When I ran  apt update, The errors happens as follows, Does somebody know how to fix it? Thank you!
`root@localhost:/etc/apt/sources.list.d# apt update
Err:1 http://apt.opennetlinux.org/debian unstable InRelease
  Temporary failure resolving 'apt.opennetlinux.org'
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: Failed to fetch http://apt.opennetlinux.org/debian/dists/unstable/InRelease  Temporary failure resolving 'apt.opennetlinux.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by paulmenzel** [comment]
What was the problem/solution? Did you have network/DNS troubles?

    $ host apt.opennetlinux.org
    apt.opennetlinux.org is an alias for opennetlinux.org.
    opennetlinux.org has address 165.227.87.248
    opennetlinux.org has IPv6 address 2604:a880:400:d0::383c:d001
    opennetlinux.org mail is handled by 10 opennetlinux.org.
