### ISSUE TITLE
Broken links on download pages

### ISSUE THREAD

**Issue by otex** [opencomputeproject/OpenNetworkLinux#99]
http://opennetlinux.org/binaries 

Some links on the top level work, but almost everything under a subfolder leads to error page: "We're sorry, but something went wrong" or "The page you were looking for doesn't exist.".

Historical versions later than 2016.01.04.21.46.18cc76084b3104961117aa8434599c8c67a9a276/ and are broken.

**Comment by sonoble** [comment]
Hi Otek,

This is a issue with how the security is setup on the site :( I am working on a new site that will allow for better access to older images.  What image are you looking for?

**Comment by sonoble** [comment]
Hi Again Otek,

This has been corrected, please let me know if you need anything else.
